// frontend/src/public_shared/PublicShell.vue
<script setup lang="ts">
import { watch } from "vue";
import AdSlot from "./AdSlot.vue";
import BrandMark from "./BrandMark.vue";
import AppToast from "@/components/AppToast.vue";
import type { Locale } from "./strings";

/** Page chrome shared by all three public mini-apps: the 720px
 *  ``container.stack`` wrapper and the header (BrandMark + language
 *  switcher). The page's own content goes in the default slot. The
 *  language is a two-way model so the host keeps a single ``locale``
 *  ref; this component owns the flag toggle and keeps
 *  ``document.documentElement.lang`` in sync. */
const locale = defineModel<Locale>("locale", { required: true });

// The sign-up / fill pages use the narrow 720px column; the chapter
// agenda opts into a wider ~1120px container for its card grid.
defineProps<{ wide?: boolean; hideAds?: boolean }>();

watch(locale, (l) => {
  document.documentElement.lang = l;
}, { immediate: true });
</script>

<template>
  <!-- The toast is a fixed overlay; keeping it outside the column means
       it doesn't count as the stack's first child and push the header
       down by one gap — which is what made this header sit 12px lower
       than the organisation's front page. -->
  <AppToast />
  <div class="stack" :class="wide ? 'container-wide' : 'container'">
    <header class="public-header">
      <slot name="brand"><BrandMark public-link /></slot>
      <div class="lang-switcher" role="group" aria-label="Language">
        <button
          type="button"
          class="flag"
          :class="{ active: locale === 'nl' }"
          aria-label="Nederlands"
          title="Nederlands"
          @click="locale = 'nl'"
        >🇳🇱</button>
        <button
          type="button"
          class="flag"
          :class="{ active: locale === 'en' }"
          aria-label="English"
          title="English"
          @click="locale = 'en'"
        >🇬🇧</button>
      </div>
    </header>

    <slot />

    <!-- Advertising, on the pages that carry any. ``AdSlot`` decides:
         organisation-branded pages get nothing at all. -->
    <AdSlot :locale="locale" :hide="hideAds" />
  </div>
</template>

<style scoped>
/* ``.container``, ``.stack`` and ``.public-header`` come from the
 * global theme.css that every mini-app imports in its ``main.ts`` —
 * the header rule is shared with the organisation's front page. */
.lang-switcher {
  display: flex;
  gap: 0.25rem;
  background: var(--brand-surface);
  border: 1px solid var(--brand-border);
  border-radius: 999px;
  padding: 0.25rem;
}
.flag {
  background: none;
  border: 2px solid transparent;
  cursor: pointer;
  padding: 0.25rem 0.5rem;
  border-radius: 999px;
  font-size: 1.1rem;
  line-height: 1;
  opacity: 0.4;
  filter: grayscale(0.6);
  transition: opacity 120ms, filter 120ms, border-color 120ms, background 120ms;
}
.flag:hover { opacity: 0.85; filter: grayscale(0.2); }
/* No accent here. The switcher is chrome, and full opacity against its
 * dimmed neighbour is enough to show which language is on; an accent
 * ring put a second target on the page competing with the button the
 * visitor came to press. */
.flag.active {
  opacity: 1;
  filter: none;
  background: var(--brand-bg);
  border-color: var(--brand-border);
}
</style>

// frontend/src/public_shared/PublicShell.svelte
<script lang="ts">
import type { Snippet } from "svelte";

import AdSlot from "./AdSlot.svelte";
import BrandMark from "./BrandMark.svelte";
import Colophon from "./Colophon.svelte";
import AppToast from "@/components/AppToast.svelte";
import type { Locale } from "./strings";

/** Page chrome shared by all the public mini-apps: the 720px
 *  ``container.stack`` wrapper and the header (BrandMark + language
 *  switcher). The page's own content goes in the default slot. The
 *  language is bound both ways so the host keeps a single ``locale``;
 *  this component owns the flag toggle and keeps
 *  ``document.documentElement.lang`` in sync. */
let {
  locale = $bindable(),
  wide,
  hideAds,
  brand,
  children,
}: {
  locale: Locale;
  /** The sign-up and fill pages use the narrow 720px column; the
   *  chapter agenda opts into a wider ~1120px container for its card
   *  grid. */
  wide?: boolean;
  hideAds?: boolean;
  brand?: Snippet;
  children: Snippet;
} = $props();

$effect(() => {
  document.documentElement.lang = locale;
});
</script>

<!-- The toast is a fixed overlay; keeping it outside the column means
     it does not count as the stack's first child and push the header
     down by one gap, which is what made this header sit 12px lower than
     the organisation's front page. -->
<AppToast />
<div class="stack {wide ? 'container-wide' : 'container'}">
  <header class="public-header">
    {#if brand}{@render brand()}{:else}<BrandMark publicLink />{/if}
    <div class="lang-switcher" role="group" aria-label="Language">
      <button
        type="button"
        class="flag"
        class:active={locale === "nl"}
        aria-label="Nederlands"
        title="Nederlands"
        onclick={() => (locale = "nl")}
      >🇳🇱</button>
      <button
        type="button"
        class="flag"
        class:active={locale === "en"}
        aria-label="English"
        title="English"
        onclick={() => (locale = "en")}
      >🇬🇧</button>
    </div>
  </header>

  {@render children()}

  <!-- Advertising, on the pages that carry any. ``AdSlot`` decides:
       organisation-branded pages get nothing at all. -->
  <AdSlot {locale} hide={hideAds} />

  <!-- The colophon, on house-brand pages only. ``Colophon`` decides,
       the same test the ad slot uses. -->
  <Colophon {locale} />
</div>

<style>
/* ``.container``, ``.stack`` and ``.public-header`` come from the
 * global theme.css that every mini-app imports in its ``main.ts``:
 * the header rule is shared with the organisation's front page. */
.lang-switcher {
  display: flex;
  gap: 0.25rem;
  background: var(--brand-surface);
  border: 1px solid var(--brand-border);
  border-radius: 999px;
  padding: 0.25rem;
}
.flag {
  background: none;
  border: 2px solid transparent;
  cursor: pointer;
  padding: 0.25rem 0.5rem;
  border-radius: 999px;
  font-size: 1.1rem;
  line-height: 1;
  opacity: 0.4;
  filter: grayscale(0.6);
  transition: opacity 120ms, filter 120ms, border-color 120ms, background 120ms;
}
.flag:hover { opacity: 0.85; filter: grayscale(0.2); }
/* No accent here. The switcher is chrome, and full opacity against its
 * dimmed neighbour is enough to show which language is on; an accent
 * ring put a second target on the page competing with the button the
 * visitor came to press. */
.flag.active {
  opacity: 1;
  filter: none;
  background: var(--brand-bg);
  border-color: var(--brand-border);
}
</style>
