// frontend/src/components/AppConfirmDialog.vue
<script setup lang="ts">
/** Renders whatever ``useConfirms().ask`` last asked (``lib/confirms``).
 *  Mounted once in ``App.vue``, the way PrimeVue's ConfirmDialog was. */
import { computed } from "vue";

import AppButton from "@/components/AppButton.vue";
import AppDialog from "@/components/AppDialog.vue";
import AppIcon from "@/components/AppIcon.vue";
import { useConfirmRequest } from "@/lib/confirms";

const { state, accept, reject } = useConfirmRequest();
const open = computed({
  get: () => state.request !== null,
  // The dialog closes itself on Escape and on the close button; either
  // is a decision not to go ahead.
  set: (v: boolean) => {
    if (!v) reject();
  },
});
</script>

<template>
  <AppDialog v-if="state.request" v-model:visible="open" :header="state.request.header">
    <p class="confirm-message">
      <AppIcon v-if="state.request.icon" :name="state.request.icon" />
      <span>{{ state.request.message }}</span>
    </p>
    <template #footer>
      <AppButton :label="state.request.rejectLabel" severity="secondary" text @click="reject" />
      <AppButton :label="state.request.acceptLabel" @click="accept" />
    </template>
  </AppDialog>
</template>

<style scoped>
.confirm-message {
  display: flex;
  align-items: flex-start;
  gap: 0.5rem;
  margin: 0;
}
</style>

// frontend/src/components/AppConfirmDialog.svelte
<script lang="ts">
/** Renders whatever ``useConfirms().ask`` last asked (``lib/confirms``).
 *  Mounted once in ``App.vue``, the way PrimeVue's ConfirmDialog was. */
import AppButton from "@/components/AppButton.svelte";
import AppDialog from "@/components/AppDialog.svelte";
import AppIcon from "@/components/AppIcon.svelte";
import { acceptConfirm, currentConfirm, rejectConfirm } from "@/lib/confirms.svelte";

const request = $derived(currentConfirm());

// The dialog closes itself on Escape and on the close button; either is
// a decision not to go ahead.
let open = $derived(request !== null);
</script>

{#if request}
  <AppDialog
    bind:visible={
      () => open,
      (v) => {
        if (!v) rejectConfirm();
      }
    }
    header={request.header}
  >
    <p class="confirm-message">
      {#if request.icon}<AppIcon name={request.icon} />{/if}
      <span>{request.message}</span>
    </p>
    {#snippet footer()}
      <AppButton label={request.rejectLabel} severity="secondary" text onclick={rejectConfirm} />
      <AppButton label={request.acceptLabel} onclick={acceptConfirm} />
    {/snippet}
  </AppDialog>
{/if}

<style>
.confirm-message {
  display: flex;
  align-items: flex-start;
  gap: 0.5rem;
  margin: 0;
}
</style>
