// frontend/src/components/AppCard.vue
<script setup lang="ts">
const props = withDefaults(
  defineProps<{
    /** Apply the standard `.stack` vertical-gap layout. Default true. */
    stack?: boolean;
    /** Underlying tag — switch to `form`, `section`, etc. when needed. */
    tag?: string;
  }>(),
  { stack: true, tag: "div" },
);
</script>

<template>
  <component :is="props.tag" :class="['card', { stack: props.stack }]">
    <slot />
  </component>
</template>

// frontend/src/components/AppCard.svelte
<script lang="ts">
import type { Snippet } from "svelte";

/** A card: the app's one panel. ``stack`` is the standard vertical-gap
 *  layout, on unless a caller says otherwise; ``tag`` swaps the element
 *  for a ``form`` or a ``section`` where the markup should say so. */
const {
  stack = true,
  tag = "div",
  children,
}: { stack?: boolean; tag?: string; children: Snippet } = $props();
</script>

<svelte:element this={tag} class="card" class:stack>
  {@render children()}
</svelte:element>
