// frontend/src/components/PublicHeader.svelte
<script lang="ts">
import BrandMark from "@/public_shared/BrandMark.svelte";
import LanguageSwitcher from "@/components/LanguageSwitcher.svelte";

/** The public header for pages that carry no page-specific identity
 * (the feedback form). Pages that do, an organisation's front page or a
 * chapter's agenda, use ``PublicIdentity`` in the same
 * ``.public-header`` row instead. */
</script>

<header class="public-header">
  <BrandMark publicLink />
  <LanguageSwitcher />
</header>

// frontend/src/components/PublicHeader.vue
<script setup lang="ts">
import BrandMark from "@/public_shared/BrandMark.vue";
import LanguageSwitcher from "@/components/LanguageSwitcher.vue";

/** The public header for pages that carry no page-specific identity
 * (the feedback form). Pages that do — an organisation's front page, a
 * chapter's agenda — use ``PublicIdentity`` in the same
 * ``.public-header`` row instead. */
</script>

<template>
  <header class="public-header">
    <BrandMark public-link />
    <LanguageSwitcher />
  </header>
</template>
