// frontend/src/components/SearchInput.svelte
<script lang="ts">
/** A search field with the magnifier sitting inside it. The icon and
 *  its clearance were PrimeVue's ``IconField`` / ``InputIcon``, which
 *  is a wrapper, an absolutely-positioned icon, and padding on the
 *  input. That is cheaper written here than imported. */
import AppInput from "@/components/AppInput.svelte";
import AppIcon from "@/components/AppIcon.svelte";

let { value = $bindable(""), placeholder }: { value: string; placeholder: string } = $props();
</script>

<div class="icon-field">
  <AppIcon name="search" />
  <AppInput bind:value {placeholder} fluid />
</div>

<style>
.icon-field {
  position: relative;
  display: block;
}
.icon-field :global(.app-icon) {
  position: absolute;
  top: 50%;
  inset-inline-start: 0.75rem;
  margin-top: -0.5rem;
  color: var(--brand-text-muted);
  z-index: 1;
}
/* Twice the field's own inline padding, plus the icon, so the text
 * starts clear of it. */
.icon-field :global(.app-input) {
  padding-inline-start: 2.5rem;
}
</style>

// frontend/src/components/SearchInput.vue
<script setup lang="ts">
/** A search field with the magnifier sitting inside it. The icon and
 *  its clearance were PrimeVue's ``IconField`` / ``InputIcon``, which
 *  is a wrapper, an absolutely-positioned icon, and padding on the
 *  input. That is cheaper written here than imported. */
import AppInput from "@/components/AppInput.vue";
import AppIcon from "@/components/AppIcon.vue";

defineProps<{
  modelValue: string;
  placeholder: string;
}>();

defineEmits<{ "update:modelValue": [value: string] }>();
</script>

<template>
  <div class="icon-field">
    <AppIcon name="search" class="field-icon" />
    <AppInput
      :model-value="modelValue"
      :placeholder="placeholder"
      fluid
      @update:model-value="(v: string | null | undefined) => $emit('update:modelValue', v ?? '')"
    />
  </div>
</template>

<style scoped>
.icon-field {
  position: relative;
  display: block;
}
.field-icon {
  position: absolute;
  top: 50%;
  inset-inline-start: 0.75rem;
  margin-top: -0.5rem;
  color: var(--brand-text-muted);
  z-index: 1;
}
/* Twice the field's own inline padding, plus the icon, so the text
 * starts clear of it. */
.icon-field :deep(.app-input) {
  padding-inline-start: 2.5rem;
}
</style>
