// frontend/src/pages/ChaptersPage.vue
<script setup lang="ts">
import AppButton from "@/components/AppButton.vue";
import AppInput from "@/components/AppInput.vue";
import SelectField from "@/components/SelectField.vue";
import { useQueryClient } from "@tanstack/vue-query";
import { computed, ref } from "vue";
import { useI18n } from "@/i18n";
import AppCard from "@/components/AppCard.vue";
import AppDialog from "@/components/AppDialog.vue";
import AppHeader from "@/components/AppHeader.vue";
import AppSkeleton from "@/components/AppSkeleton.vue";
import ChapterPicker from "@/components/ChapterPicker.vue";
import CityPicker from "@/components/CityPicker.vue";
import { brand } from "@/lib/branding";
import EditableList from "@/components/EditableList.vue";
import {
  type Chapter,
  chapterList,
  getChapterUsage,
  useArchiveChapter,
  useChapters,
  useCreateChapter,
  useRestoreChapter,
  useUpdateChapter,
} from "@/composables/useChapters";
import { useDialog } from "@/composables/useDialog";
import { can as permCan } from "@/lib/permissions";
import { useToasts } from "@/lib/toasts";
import { useAuthStore } from "@/stores/auth";

const { t } = useI18n();
const auth = useAuthStore();
const toasts = useToasts();
const qc = useQueryClient();

const canManageChapters = computed(() => permCan(auth.user, "create_chapter"));

// One list, archived rows included. ``onCreateFromAddBar`` needs them
// to find a soft-deleted chapter whose name the admin just retyped —
// without that the restore branch couldn't see the candidate and Enter
// would 409 with "name already exists" forever. The table wants only
// the live ones, and every row carries ``archived``, so that is a
// filter rather than a second request for a subset of what is already
// in hand.
const chaptersQuery = useChapters({ includeArchived: true });
const chapters = computed(() => chapterList(chaptersQuery).value.filter((c) => !c.archived));
const createChapter = useCreateChapter();
const updateChapter = useUpdateChapter();
const archiveChapter = useArchiveChapter();
const restoreChapter = useRestoreChapter();

const loaded = computed(() => !chaptersQuery.isLoading.value);

// --- Edit-chapter dialog (name + city) -------------------------------
const editDialog = useDialog<Chapter>();
const editName = ref<string>("");
const editSlug = ref<string>("");
const editCity = ref<{ city: string | null; city_lat: number | null; city_lon: number | null }>({
  city: null,
  city_lat: null,
  city_lon: null,
});

function openEditChapter(a: Chapter) {
  editName.value = a.name;
  editSlug.value = a.slug;
  editCity.value = { city: a.city, city_lat: a.city_lat, city_lon: a.city_lon };
  editDialog.openWith(a);
}

async function submitEditChapter() {
  const target = editDialog.target.value;
  if (!target) return;
  const trimmed = editName.value.trim();
  if (!trimmed) {
    toasts.warn(t("chapters.fillName"));
    return;
  }
  try {
    await editDialog.submit(async () => {
      await updateChapter.mutateAsync({
        id: target.id,
        payload: {
          name: trimmed,
          slug: editSlug.value.trim(),
          city: editCity.value.city,
          city_lat: editCity.value.city_lat,
          city_lon: editCity.value.city_lon,
        },
      });
      toasts.success(t("chapters.editedToast"));
    });
  } catch (e) {
    toasts.error(e instanceof Error ? e.message : t("chapters.editFail"));
  }
}

// --- Delete-chapter dialog (with optional reassignment) --------------
const deleteDialog = useDialog<Chapter>();
const deleteUsage = ref<{ users: number; events: number }>({ users: 0, events: 0 });
const deleteReassignUsersTo = ref<Chapter | null>(null);
const deleteReassignEventsTo = ref<Chapter | null>(null);
// Id of the chapter whose usage we're currently fetching, so the
// trash icon shows a spinner instead of looking frozen on slow
// connections (UX principle 11: keep the feedback gap closed).
const usageLoadingFor = ref<string | null>(null);

const otherChapters = computed(() =>
  chapters.value.filter((a) => a.id !== deleteDialog.target.value?.id),
);

async function onPickedChapterFromAddBar(a: Chapter) {
  if (!a.archived) return;
  try {
    await restoreChapter.mutateAsync(a.id);
    toasts.success(t("chapters.restoredToast", { name: a.name }));
  } catch {
    toasts.error(t("chapters.restoreFail"));
  }
}

function normaliseChapterName(name: string): string {
  // Mirror backend services.chapters.normalise_name — strip + collapse
  // internal whitespace so " Den   Haag " matches "Den Haag" exactly.
  return name.trim().split(/\s+/).join(" ");
}

async function onCreateFromAddBar(name: string) {
  // If the typed name exactly matches a soft-deleted chapter
  // (whitespace-normalised + case-insensitive), Enter restores that
  // one rather than creating a duplicate. Without this branch the
  // dupe-name guard would block the create, and the archived chapter
  // would be permanently unreachable from the keyboard.
  try {
    const normalised = normaliseChapterName(name);
    // Refresh the list and search it for a soft-deleted match: the
    // table renders the live rows, but the archived ones are in the
    // same response.
    const withArchived = await chaptersQuery.refetch();
    const lower = normalised.toLowerCase();
    const archivedMatch = (withArchived.data ?? []).find(
      (a) => a.archived && a.name.toLowerCase() === lower,
    );
    if (archivedMatch) {
      await restoreChapter.mutateAsync(archivedMatch.id);
      toasts.success(t("chapters.restoredToast", { name: archivedMatch.name }));
      return;
    }
    await createChapter.mutateAsync(normalised);
    toasts.success(t("chapters.createdToast", { name: normalised }));
  } catch {
    toasts.error(t("chapters.createFail"));
  }
}

async function openDeleteDialog(a: Chapter) {
  deleteReassignUsersTo.value = null;
  deleteReassignEventsTo.value = null;
  usageLoadingFor.value = a.id;
  try {
    deleteUsage.value = await getChapterUsage(a.id);
  } catch {
    deleteUsage.value = { users: 0, events: 0 };
  } finally {
    usageLoadingFor.value = null;
  }
  deleteDialog.openWith(a);
}

async function submitDelete() {
  const target = deleteDialog.target.value;
  if (!target) return;
  try {
    await deleteDialog.submit(async () => {
      await archiveChapter.mutateAsync({
        id: target.id,
        reassign: {
          users: deleteReassignUsersTo.value?.id ?? null,
          events: deleteReassignEventsTo.value?.id ?? null,
        },
      });
      toasts.success(t("chapters.archivedToast"));
      // Reassignment changes user→chapter membership server-side;
      // invalidate so the Users page refetches on next visit.
      void qc.invalidateQueries({ queryKey: ["users"] });
    });
  } catch {
    toasts.error(t("chapters.archiveFail"));
  }
}
</script>

<template>
  <AppHeader />
  <div class="container-wide stack">
    <h1>{{ t("chapters.title") }}</h1>
    <p class="muted">{{ t("chapters.intro") }}</p>

    <AppCard>
      <AppSkeleton v-if="!loaded" :rows="3" />
      <template v-else>
        <ChapterPicker
        :placeholder="t('chapters.addPlaceholder')"
        :archived-only="true"
        :disabled="!canManageChapters"
        leading-icon="plus"
        @pick="onPickedChapterFromAddBar"
        @create="onCreateFromAddBar"
      />
      <EditableList
        :items="chapters"
        :item-label="(a: Chapter) => a.name"
        :item-key="(a: Chapter) => a.id"
        :loading-key="usageLoadingFor"
        :readonly="!canManageChapters"
        @remove="openDeleteDialog"
      >
        <template #row="{ item }">
          <div class="chapter-row">
            <span class="chapter-name">
              {{ (item as Chapter).name }}
              <span v-if="(item as Chapter).city" class="muted chapter-city">
                · {{ (item as Chapter).city }}
              </span>
            </span>
            <AppButton
              icon="pencil"
              size="small"
              severity="secondary"
              text
              :disabled="!canManageChapters"
              :aria-label="t('common.edit')"
              @click="openEditChapter(item as Chapter)"
            />
          </div>
        </template>
      </EditableList>
      </template>
    </AppCard>

    <AppDialog
      v-model:visible="deleteDialog.open.value"
      :header="t('chapters.deleteDialogTitle', { name: deleteDialog.target.value?.name ?? '' })"
      width="480px"
    >
      <p class="muted dialog-text">{{ t("chapters.deleteDialogBody") }}</p>
      <label v-if="deleteUsage.users > 0" class="reassign-label">
        {{ t("chapters.deleteUsersLabel", { n: deleteUsage.users }) }}
        <SelectField
          v-model="deleteReassignUsersTo"
          :options="otherChapters"
          option-label="name"
          show-clear
          :placeholder="t('chapters.deleteLeaveOrphaned')"
          fluid
        />
      </label>
      <label v-if="deleteUsage.events > 0" class="reassign-label">
        {{ t("chapters.deleteEventsLabel", { n: deleteUsage.events }) }}
        <SelectField
          v-model="deleteReassignEventsTo"
          :options="otherChapters"
          option-label="name"
          show-clear
          :placeholder="t('chapters.deleteLeaveOrphaned')"
          fluid
        />
      </label>
      <p v-if="deleteUsage.users === 0 && deleteUsage.events === 0" class="muted dialog-text">
        {{ t("chapters.deleteNoDeps") }}
      </p>
      <template #footer>
        <AppButton :label="t('common.cancel')" severity="secondary" text @click="deleteDialog.close()" />
        <AppButton :label="t('chapters.archive')" :loading="deleteDialog.submitting.value" @click="submitDelete" />
      </template>
    </AppDialog>

    <AppDialog
      v-model:visible="editDialog.open.value"
      :header="t('chapters.editDialogTitle', { name: editDialog.target.value?.name ?? '' })"
    >
      <p class="muted dialog-text">{{ t("chapters.editDialogBody") }}</p>
      <AppInput v-model="editName" :placeholder="t('chapters.namePlaceholder')" fluid />
      <AppInput v-model="editSlug" :placeholder="t('chapters.slugPlaceholder')" fluid />
      <p class="muted dialog-text">
        {{ t("chapters.slugHelp", { tenant: brand().slug, slug: editSlug || "…" }) }}
      </p>
      <CityPicker v-model="editCity" :placeholder="t('chapters.cityPlaceholder')" />
      <template #footer>
        <AppButton :label="t('common.cancel')" severity="secondary" text @click="editDialog.close()" />
        <AppButton :label="t('common.save')" :loading="editDialog.submitting.value" @click="submitEditChapter" />
      </template>
    </AppDialog>
  </div>
</template>

<style scoped>
.dialog-text {
  margin: 0;
}
.reassign-label {
  display: flex;
  flex-direction: column;
  gap: 0.375rem;
  font-size: 0.875rem;
  color: var(--brand-text);
}
.chapter-row {
  display: flex;
  align-items: center;
  gap: 0.375rem;
  width: 100%;
}
.chapter-name {
  flex: 1;
  min-width: 0;
}
</style>

// frontend/src/pages/ChaptersPage.svelte
<script lang="ts">
import AppButton from "@/components/AppButton.svelte";
import AppCard from "@/components/AppCard.svelte";
import AppDialog from "@/components/AppDialog.svelte";
import AppHeader from "@/components/AppHeader.svelte";
import AppInput from "@/components/AppInput.svelte";
import AppSkeleton from "@/components/AppSkeleton.svelte";
import ChapterPicker from "@/components/ChapterPicker.svelte";
import CityPicker from "@/components/CityPicker.svelte";
import EditableList from "@/components/EditableList.svelte";
import SelectField from "@/components/SelectField.svelte";
import {
  archiveChapter,
  type Chapter,
  chapterUsage,
  chaptersQuery,
  createChapter,
  restoreChapter,
  sortedChapters,
  updateChapter,
} from "@/composables/useChapters.svelte";
import { dialog } from "@/composables/useDialog.svelte";
import { t } from "@/i18n.svelte";
import { brand } from "@/lib/branding";
import { can } from "@/lib/permissions";
import { queryClient } from "@/lib/query-client";
import { useToasts } from "@/lib/toasts";
import { auth } from "@/stores/auth.svelte";

/** The organisation's chapters: add, rename, give a city, archive. */
const toasts = useToasts();
const canManage = $derived(can(auth.user, "create_chapter"));

// One list, archived rows included. The add bar needs them to find a
// chapter whose name an admin just retyped: without that the restore
// branch could not see the candidate and Enter would refuse the name
// forever. The table wants the live ones, and every row says whether it
// is archived, so that is a filter rather than a second request for
// part of what is already in hand.
const query = chaptersQuery({ includeArchived: true });
const chapters = $derived(sortedChapters(query.data).filter((c) => !c.archived));

const create = createChapter();
const update = updateChapter();
const archive = archiveChapter();
const restore = restoreChapter();

// --- Rename, and give it a city -------------------------------------
const editDialog = dialog<Chapter>();
let editName = $state("");
let editSlug = $state("");
let editCity = $state<{ city: string | null; city_lat: number | null; city_lon: number | null }>({
  city: null,
  city_lat: null,
  city_lon: null,
});

function openEdit(c: Chapter): void {
  editName = c.name;
  editSlug = c.slug;
  editCity = { city: c.city, city_lat: c.city_lat, city_lon: c.city_lon };
  editDialog.openWith(c);
}

async function submitEdit(): Promise<void> {
  const target = editDialog.target;
  if (!target) return;
  const trimmed = editName.trim();
  if (!trimmed) {
    toasts.warn(t("chapters.fillName"));
    return;
  }
  try {
    await editDialog.submit(async () => {
      await update.run({
        id: target.id,
        payload: {
          name: trimmed,
          slug: editSlug.trim(),
          city: editCity.city,
          city_lat: editCity.city_lat,
          city_lon: editCity.city_lon,
        },
      });
      toasts.success(t("chapters.editedToast"));
    });
  } catch (e) {
    toasts.error(e instanceof Error ? e.message : t("chapters.editFail"));
  }
}

// --- Archive, and hand on what pointed at it -------------------------
const deleteDialog = dialog<Chapter>();
let usage = $state<{ users: number; events: number }>({ users: 0, events: 0 });
let reassignUsersTo = $state<Chapter | null>(null);
let reassignEventsTo = $state<Chapter | null>(null);
/** The chapter whose usage is being fetched, so its trash button spins
 *  rather than looking frozen on a slow connection. */
let usageLoadingFor = $state<string | null>(null);

const otherChapters = $derived(chapters.filter((c) => c.id !== deleteDialog.target?.id));

async function openDelete(c: Chapter): Promise<void> {
  reassignUsersTo = null;
  reassignEventsTo = null;
  usageLoadingFor = c.id;
  try {
    usage = await chapterUsage(c.id);
  } catch {
    usage = { users: 0, events: 0 };
  } finally {
    usageLoadingFor = null;
  }
  deleteDialog.openWith(c);
}

async function submitDelete(): Promise<void> {
  const target = deleteDialog.target;
  if (!target) return;
  try {
    await deleteDialog.submit(async () => {
      await archive.run({
        id: target.id,
        reassign: { users: reassignUsersTo?.id ?? null, events: reassignEventsTo?.id ?? null },
      });
      toasts.success(t("chapters.archivedToast"));
      // Handing rows on changes who belongs to what, so the users page
      // refetches on its next visit.
      void queryClient.invalidateQueries({ queryKey: ["users"] });
    });
  } catch {
    toasts.error(t("chapters.archiveFail"));
  }
}

// --- The add bar -----------------------------------------------------
async function onPicked(c: Chapter): Promise<void> {
  if (!c.archived) return;
  try {
    await restore.run(c.id);
    toasts.success(t("chapters.restoredToast", { name: c.name }));
  } catch {
    toasts.error(t("chapters.restoreFail"));
  }
}

/** The same normalisation the backend does, so " Den   Haag " and
 *  "Den Haag" are one name here too. */
function normaliseName(name: string): string {
  return name.trim().split(/\s+/).join(" ");
}

async function onCreate(name: string): Promise<void> {
  // A typed name that matches an archived chapter restores that one
  // rather than making a second. Without this the duplicate-name guard
  // would refuse the create, and the archived chapter would be
  // unreachable from the keyboard for good.
  try {
    const normalised = normaliseName(name);
    const lower = normalised.toLowerCase();
    // Asked again rather than read from the cache: the chapter being
    // retyped may have been archived from another tab a moment ago.
    const archivedMatch = ((await query.refetch()) ?? []).find(
      (c) => c.archived && c.name.toLowerCase() === lower,
    );
    if (archivedMatch) {
      await restore.run(archivedMatch.id);
      toasts.success(t("chapters.restoredToast", { name: archivedMatch.name }));
      return;
    }
    await create.run(normalised);
    toasts.success(t("chapters.createdToast", { name: normalised }));
  } catch {
    toasts.error(t("chapters.createFail"));
  }
}
</script>

<AppHeader />
<div class="container-wide stack">
  <h1>{t("chapters.title")}</h1>
  <p class="muted">{t("chapters.intro")}</p>

  <AppCard>
    {#if query.isPending}
      <AppSkeleton rows={3} />
    {:else}
      <ChapterPicker
        placeholder={t("chapters.addPlaceholder")}
        archivedOnly
        disabled={!canManage}
        leadingIcon="plus"
        onpick={onPicked}
        oncreate={onCreate}
      />
      <EditableList
        items={chapters}
        itemLabel={(c) => c.name}
        itemKey={(c) => c.id}
        loadingKey={usageLoadingFor}
        readonly={!canManage}
        onremove={openDelete}
      >
        {#snippet row({ item })}
          <div class="chapter-row">
            <span class="chapter-name">
              {item.name}
              {#if item.city}<span class="muted chapter-city"> · {item.city}</span>{/if}
            </span>
            <AppButton
              icon="pencil"
              size="small"
              severity="secondary"
              text
              disabled={!canManage}
              ariaLabel={t("common.edit")}
              onclick={() => openEdit(item)}
            />
          </div>
        {/snippet}
      </EditableList>
    {/if}
  </AppCard>

  <AppDialog
    bind:visible={deleteDialog.open}
    header={t("chapters.deleteDialogTitle", { name: deleteDialog.target?.name ?? "" })}
    width="480px"
  >
    <p class="muted dialog-text">{t("chapters.deleteDialogBody")}</p>
    {#if usage.users > 0}
      <label class="reassign-label">
        {t("chapters.deleteUsersLabel", { n: usage.users })}
        <SelectField
          bind:value={reassignUsersTo}
          options={otherChapters}
          optionLabel="name"
          showClear
          placeholder={t("chapters.deleteLeaveOrphaned")}
          fluid
        />
      </label>
    {/if}
    {#if usage.events > 0}
      <label class="reassign-label">
        {t("chapters.deleteEventsLabel", { n: usage.events })}
        <SelectField
          bind:value={reassignEventsTo}
          options={otherChapters}
          optionLabel="name"
          showClear
          placeholder={t("chapters.deleteLeaveOrphaned")}
          fluid
        />
      </label>
    {/if}
    {#if usage.users === 0 && usage.events === 0}
      <p class="muted dialog-text">{t("chapters.deleteNoDeps")}</p>
    {/if}
    {#snippet footer()}
      <AppButton
        label={t("common.cancel")}
        severity="secondary"
        text
        onclick={() => deleteDialog.close()}
      />
      <AppButton
        label={t("chapters.archive")}
        loading={deleteDialog.submitting}
        onclick={submitDelete}
      />
    {/snippet}
  </AppDialog>

  <AppDialog
    bind:visible={editDialog.open}
    header={t("chapters.editDialogTitle", { name: editDialog.target?.name ?? "" })}
  >
    <p class="muted dialog-text">{t("chapters.editDialogBody")}</p>
    <AppInput bind:value={editName} placeholder={t("chapters.namePlaceholder")} fluid />
    <AppInput bind:value={editSlug} placeholder={t("chapters.slugPlaceholder")} fluid />
    <p class="muted dialog-text">
      {t("chapters.slugHelp", { tenant: brand().slug, slug: editSlug || "…" })}
    </p>
    <CityPicker bind:value={editCity} placeholder={t("chapters.cityPlaceholder")} />
    {#snippet footer()}
      <AppButton
        label={t("common.cancel")}
        severity="secondary"
        text
        onclick={() => editDialog.close()}
      />
      <AppButton label={t("common.save")} loading={editDialog.submitting} onclick={submitEdit} />
    {/snippet}
  </AppDialog>
</div>

<style>
.dialog-text {
  margin: 0;
}
.reassign-label {
  display: flex;
  flex-direction: column;
  gap: 0.375rem;
  font-size: 0.875rem;
  color: var(--brand-text);
}
.chapter-row {
  display: flex;
  align-items: center;
  gap: 0.375rem;
  width: 100%;
}
.chapter-name {
  flex: 1;
  min-width: 0;
}
</style>
