// frontend/src/pages/ChoresEditPage.svelte
<script lang="ts">
import AppButton from "@/components/AppButton.svelte";
import AppCard from "@/components/AppCard.svelte";
import AppHeader from "@/components/AppHeader.svelte";
import AppInput from "@/components/AppInput.svelte";
import AppToggle from "@/components/AppToggle.svelte";
import ChoreEditor, { type ChoreDraft } from "@/components/ChoreEditor.svelte";
import DatePicker from "@/components/DatePicker.svelte";
import { DEFAULT_CHORE_EMOJI, firstUnusedEmoji } from "@/components/EmojiPicker.svelte";
import FormPageShell from "@/components/FormPageShell.svelte";
import ImageField from "@/components/ImageField.svelte";
import NumberStepper from "@/components/NumberStepper.svelte";
import RichTextField from "@/components/RichTextField.svelte";
import SelectField from "@/components/SelectField.svelte";
import StartAccountField from "@/components/StartAccountField.svelte";
import StartedPanel from "@/components/StartedPanel.svelte";
import RouterLink from "@/router/RouterLink.svelte";
import { bilingualField } from "@/composables/useBilingualField.svelte";
import { chaptersQuery, sortedChapters } from "@/composables/useChapters.svelte";
import { rosters } from "@/composables/useChores.svelte";
import { formDraft } from "@/composables/useFormDraft.svelte";
import { orderedList } from "@/composables/useOrderedList.svelte";
import { startMode } from "@/composables/useStartMode.svelte";
import { locale, t } from "@/i18n.svelte";
import { untrack } from "svelte";

import { ApiError } from "@/api/client";
import { go, route } from "@/router/navigation.svelte";
import { useToasts } from "@/lib/toasts";
import { auth } from "@/stores/auth.svelte";
import type { ChoreIn, RosterCreate, RosterUpdate } from "@/api/types";

/**
 * Making or changing a roster: what the chores are, how often they come
 * round, and between which dates.
 */
const { rosterId }: { rosterId?: string } = $props();

const toasts = useToasts();
const start = startMode("roster");
const chapters = chaptersQuery({ enabled: () => start.hasChapters });
const create = rosters.create();
const update = rosters.update();

const isEdit = $derived(Boolean(rosterId));
const query = rosters.single(
  () => rosterId ?? "",
  { enabled: () => Boolean(rosterId) },
);
const notFound = $derived(query.error instanceof ApiError && query.error.status === 404);

let chapterId = $state<string | null>(null);
/** Only the chapters this organiser is in: assigning to one they do not
 *  belong to is refused by the server. */
const chapterOptions = $derived.by(() => {
  const mine = new Set((auth.user?.chapters ?? []).map((c) => c.id));
  return sortedChapters(chapters.data).filter((c) => mine.has(c.id));
});

let nameNl = $state("");
let nameEn = $state("");
let descNl = $state("");
let descEn = $state("");
const title = bilingualField(
  () => ({ nl: nameNl, en: nameEn }),
  (next) => {
    nameNl = next.nl;
    nameEn = next.en;
  },
);
const body = bilingualField(
  () => ({ nl: descNl, en: descEn }),
  (next) => {
    descNl = next.nl;
    descEn = next.en;
  },
);
let imageUrl = $state<string | null>(null);
let imageArtistInstagram = $state("");
let imageField = $state<ReturnType<typeof ImageField> | null>(null);
let rosterLocale = $state<"nl" | "en">(locale() === "en" ? "en" : "nl");
let nameRequired = $state(false);
/** The switches sit behind one fold, the same one every other edit page
 *  ends with, and it starts closed every time. */
let advancedOpen = $state(false);
let periodWeeks = $state(1);
let startsOn = $state<Date | null>(null);
let endsOn = $state<Date | null>(null);
let reminderEnabled = $state(true);
let reminderDaysBefore = $state(1);
let commitHorizonDays = $state(21);
const choreList = orderedList<ChoreDraft>();
let submitting = $state(false);

// Rosters usually remind, so the switch starts on. Whether this account
// may is a separate question, and it is the one the payload asks: a
// free account has no reminder section on the form and sends no
// reminders (docs/design-paywall.md).
const sendsReminders = $derived(reminderEnabled && auth.participantMail);

const localeOptions = $derived([
  { value: "nl", label: t("chore.edit.localeNl") },
  { value: "en", label: t("chore.edit.localeEn") },
]);

// --- Date and "YYYY-MM-DD", locally, with no drift through UTC -------
function isoDate(d: Date | null): string | null {
  if (!d) return null;
  const month = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${d.getFullYear()}-${month}-${day}`;
}

function parseDate(s: string | null | undefined): Date | null {
  if (!s) return null;
  const [y, m, d] = s.split("-").map(Number);
  if (!y || !m || !d) return null;
  return new Date(y, m - 1, d);
}

// A shorter cycle leaves some days out of range, so they are dropped
// and the chores that lost one are named. The server clamps too; this
// keeps the form honest about it.
let lastPeriod = 1;
$effect(() => {
  const next = periodWeeks;
  const prev = lastPeriod;
  lastPeriod = next;
  if (next >= prev) return;
  const hi = 7 * next;
  const affected: string[] = [];
  for (const c of choreList.items) {
    const kept = c.cycle_slots.filter((s) => s < hi);
    if (kept.length !== c.cycle_slots.length) {
      affected.push(c.name || t("chore.edit.untitledChore"));
      c.cycle_slots = kept;
    }
  }
  if (affected.length) toasts.warn(t("chore.edit.slotsCleared", { names: affected.join(", ") }));
});

// --- The draft, with the dates as strings ---------------------------
interface RosterEditDraft {
  nameNl: string;
  nameEn: string;
  descNl: string;
  descEn: string;
  imageArtistInstagram: string;
  chapterId: string | null;
  rosterLocale: "nl" | "en";
  periodWeeks: number;
  startsOn: string | null;
  endsOn: string | null;
  reminderEnabled: boolean;
  reminderDaysBefore: number;
  commitHorizonDays: number;
  chores: ChoreDraft[];
}

function snapshot(): RosterEditDraft {
  return {
    nameNl,
    nameEn,
    descNl,
    descEn,
    imageArtistInstagram,
    chapterId,
    rosterLocale,
    periodWeeks,
    startsOn: isoDate(startsOn),
    endsOn: isoDate(endsOn),
    reminderEnabled,
    reminderDaysBefore,
    commitHorizonDays,
    chores: choreList.items,
  };
}

function applyDraft(d: RosterEditDraft): void {
  nameNl = d.nameNl ?? "";
  nameEn = d.nameEn ?? "";
  descNl = d.descNl ?? "";
  descEn = d.descEn ?? "";
  imageArtistInstagram = d.imageArtistInstagram ?? "";
  chapterId = d.chapterId ?? null;
  rosterLocale = d.rosterLocale ?? "nl";
  periodWeeks = d.periodWeeks ?? 1;
  startsOn = parseDate(d.startsOn);
  endsOn = parseDate(d.endsOn);
  reminderEnabled = d.reminderEnabled ?? true;
  reminderDaysBefore = d.reminderDaysBefore ?? 1;
  commitHorizonDays = d.commitHorizonDays ?? 21;
  choreList.items = (d.chores ?? []).map((c) => ({
    ...c,
    cycle_slots: [...(c.cycle_slots ?? [])],
    emoji: c.emoji ?? DEFAULT_CHORE_EMOJI,
  }));
}

const draft = formDraft<RosterEditDraft>({
  key: () => `chore-edit-draft:${rosterId ?? "new"}`,
  snapshot,
  track: snapshot,
});

let draftRestored = false;
function restoreDraftOnce(): void {
  if (draftRestored) return;
  draftRestored = true;
  const saved = draft.load();
  if (saved) applyDraft(saved);
}

// The roster arrives, its values go in, and then anything the organiser
// had half-typed goes on top: a draft is newer than what was saved.
let seeded: unknown = undefined;
$effect(() => {
  const existing = query.data;
  if (!existing || existing === seeded) return;
  seeded = existing;
  nameNl = existing.name_nl ?? "";
  nameEn = existing.name_en ?? "";
  descNl = existing.description_nl ?? "";
  descEn = existing.description_en ?? "";
  imageUrl = existing.image_url ?? null;
  imageArtistInstagram = existing.image_artist_instagram ?? "";
  rosterLocale = existing.locale;
  nameRequired = existing.name_required;
  chapterId = existing.chapter_id;
  periodWeeks = existing.period_weeks;
  startsOn = parseDate(existing.starts_on);
  endsOn = parseDate(existing.ends_on);
  reminderEnabled = existing.reminder_enabled;
  reminderDaysBefore = existing.reminder_days_before;
  commitHorizonDays = existing.commit_horizon_days;
  choreList.items = (existing.chores ?? []).map((c) => ({
    id: c.id,
    name: c.name,
    description: c.description ?? null,
    cycle_slots: [...c.cycle_slots],
    people_per_shift: c.people_per_shift,
    emoji: c.emoji ?? DEFAULT_CHORE_EMOJI,
  }));
  restoreDraftOnce();
});

// A new roster: the chapter is the one the organiser came from, or the
// only one they are in. Read once, at mount, which is what ``untrack``
// says: this is the form's starting state, not something that follows
// the route afterwards.
untrack(() => {
  if (isEdit) return;
  const fromQuery = route.query.get("chapter");
  const mine = new Set((auth.user?.chapters ?? []).map((c) => c.id));
  if (fromQuery && mine.has(fromQuery)) chapterId = fromQuery;
  else if (auth.user?.chapters?.length === 1) chapterId = auth.user.chapters[0].id;
  restoreDraftOnce();
});

// --- The chore list --------------------------------------------------
function addChore(): void {
  choreList.add({
    id: null,
    name: "",
    description: null,
    cycle_slots: [],
    people_per_shift: 1,
    // A new chore starts on an emoji no other chore is using.
    emoji: firstUnusedEmoji(choreList.items.map((c) => c.emoji)),
  });
}

function setChore(index: number, next: ChoreDraft): void {
  const prev = choreList.items[index];
  // Emojis stay unique: picking one another chore already has swaps
  // them, handing that chore this one's previous emoji.
  if (next.emoji !== prev.emoji) {
    const clash = choreList.items.findIndex((c, i) => i !== index && c.emoji === next.emoji);
    if (clash !== -1) {
      choreList.replaceAt(clash, { ...choreList.items[clash], emoji: prev.emoji });
    }
  }
  choreList.replaceAt(index, next);
}

// --- Leaving, and saving ---------------------------------------------
function cancel(): void {
  draft.clear();
  if (start.cancel()) return;
  void go(isEdit && rosterId ? `/chore/${rosterId}/details` : "/chore");
}

async function submit(): Promise<void> {
  // The title is required in the roster's own language; the other one
  // is an optional translation.
  const primaryName = (rosterLocale === "en" ? nameEn : nameNl).trim();
  if (!primaryName) {
    toasts.warn(t("chore.edit.fillName"));
    return;
  }
  if (start.hasChapters && !chapterId) {
    toasts.warn(t("chore.edit.fillChapter"));
    return;
  }
  if (start.active && !start.validate()) return;
  if (!startsOn) {
    toasts.warn(t("chore.edit.fillStartsOn"));
    return;
  }
  if (choreList.items.some((c) => !c.name.trim())) {
    toasts.warn(t("chore.edit.fillChoreName"));
    return;
  }

  submitting = true;
  try {
    const payload: RosterCreate | RosterUpdate = {
      chapter_id: start.chapterFor(chapterId),
      name_nl: nameNl.trim() || null,
      name_en: nameEn.trim() || null,
      description_nl: descNl.trim() || null,
      description_en: descEn.trim() || null,
      image_artist_instagram: imageArtistInstagram.trim() || null,
      locale: rosterLocale,
      location: null,
      latitude: null,
      longitude: null,
      period_weeks: periodWeeks,
      starts_on: isoDate(startsOn) as string,
      ends_on: isoDate(endsOn),
      name_required: nameRequired,
      reminder_enabled: sendsReminders,
      reminder_days_before: reminderDaysBefore,
      commit_horizon_days: commitHorizonDays,
      chores: choreList.items.map(
        (c): ChoreIn => ({
          id: c.id,
          name: c.name.trim(),
          description: c.description,
          cycle_slots: c.cycle_slots,
          people_per_shift: c.people_per_shift,
          emoji: c.emoji,
        }),
      ),
    };

    if (start.active) {
      // No session: the public link in the answer is the whole result,
      // and there is no details page to land on. A refusal has already
      // been explained, and the draft stays so it can be tried again.
      if (await start.submit(payload)) draft.clear();
      return;
    }

    const result =
      isEdit && rosterId
        ? await update.run({ id: rosterId, payload })
        : await create.run(payload);
    await imageField?.flushPendingUpload(result.id);
    draft.clear();
    void go(`/chore/${result.id}/details`);
  } catch {
    toasts.error(t("chore.edit.saveFailed"));
  } finally {
    submitting = false;
  }
}
</script>

{#if notFound}
  <AppHeader />
  <div class="container-wide stack">
    <AppCard>
      <h2>{t("chore.edit.notFoundTitle")}</h2>
      <p class="muted">{t("chore.edit.notFoundBody")}</p>
      <RouterLink to="/chore" class="back-link">{t("chore.edit.backToList")}</RouterLink>
    </AppCard>
  </div>
{:else if query.error}
  <AppHeader />
  <div class="container-wide stack">
    <AppCard>
      <p>{t("chore.edit.loadFailed")}</p>
    </AppCard>
  </div>
{:else if start.started}
  <StartedPanel started={start.started} email={start.email} />
{:else}
  <FormPageShell
    title={isEdit ? t("chore.edit.editTitle") : t("chore.edit.newTitle")}
    submitLabel={isEdit ? t("chore.edit.save") : t("chore.edit.create")}
    {submitting}
    onsubmit={submit}
    oncancel={cancel}
  >
    <section class="form-section">
      {#if start.active}<StartAccountField bind:value={start.email} />{/if}
      <AppInput
        bind:value={title.value}
        placeholder={title.fallback || t("chore.edit.namePlaceholder")}
        fluid
      />
      <RichTextField
        bind:value={body.value}
        placeholder={t("chore.edit.descriptionPlaceholder")}
        fallbackHtml={body.fallback || null}
      />
      {#if start.hasChapters}
        <SelectField
          bind:value={chapterId}
          options={chapterOptions}
          optionLabel="name"
          optionValue="id"
          placeholder={t("chore.edit.chapterPlaceholder")}
          disabled={chapterOptions.length === 1 && chapterId !== null}
          fluid
        />
      {/if}
    </section>

    <!-- Uploading writes to the row it belongs to, which takes a
         session the visitor does not have yet. -->
    {#if !start.active}
      <ImageField
        bind:this={imageField}
        resource="chore"
        entityId={rosterId ?? null}
        bind:imageUrl
        bind:artist={imageArtistInstagram}
      />
    {/if}

    <section class="form-section">
      <h2 class="section-heading">{t("chore.edit.recurrenceHeading")}</h2>
      <p class="muted section-explainer">{t("chore.edit.recurrenceExplainer")}</p>

      <div class="stepper-row">
        <NumberStepper
          bind:value={periodWeeks}
          min={1}
          max={8}
          ariaLabel={t("chore.edit.periodWeeks")}
        />
      </div>

      <div class="date-row">
        <div class="field">
          <DatePicker
            bind:modelValue={startsOn}
            locale={locale()}
            dateFormat="dd-mm-yy"
            placeholder={t("chore.edit.startDatePlaceholder")}
            fluid
          />
        </div>
        <div class="field">
          <DatePicker
            bind:modelValue={endsOn}
            locale={locale()}
            dateFormat="dd-mm-yy"
            showButtonBar
            placeholder={t("chore.edit.endsOnPlaceholder")}
            fluid
          />
        </div>
      </div>
    </section>

    <section class="form-section">
      <h2 class="section-heading">{t("chore.edit.choresHeading")}</h2>
      <p class="muted section-explainer">{t("chore.edit.choresExplainer")}</p>

      {#if choreList.items.length === 0}
        <div class="empty muted">{t("chore.edit.noChoresYet")}</div>
      {/if}

      <div class="chores-stack">
        {#each choreList.items as c, idx (c.id ?? `new-${idx}`)}
          <ChoreEditor
            value={c}
            {periodWeeks}
            canMoveUp={idx > 0}
            canMoveDown={idx < choreList.items.length - 1}
            onchange={(next) => setChore(idx, next)}
            ondelete={() => choreList.removeAt(idx)}
            onmoveUp={() => choreList.move(idx, -1)}
            onmoveDown={() => choreList.move(idx, 1)}
          />
        {/each}
      </div>

      <AppButton
        type="button"
        label={t("chore.edit.addChore")}
        icon="plus"
        severity="secondary"
        onclick={addChore}
      />
    </section>

    <!-- Every switch, folded away: the thing itself above it, the page
         language below. One fold on all six products. -->
    <details
      class="advanced"
      open={advancedOpen}
      ontoggle={(e) => (advancedOpen = (e.target as HTMLDetailsElement).open)}
    >
      <summary>{advancedOpen ? t("common.advancedHide") : t("common.advancedShow")}</summary>

      <!-- Off by default: a name real or not is what the contract
           offers, so an empty box is an answer. A roster is the one
           place a nameless sign-up is hard to use, which makes this the
           switch an organiser is likeliest to reach for. -->
      <section class="form-section">
        <label class="toggle-row" for="nameRequiredToggle">
          <AppToggle bind:checked={nameRequired} inputId="nameRequiredToggle" />
          <h2 class="section-heading">{t("common.nameRequired")}</h2>
        </label>
        <p class="muted section-explainer">{t("common.nameRequiredExplainer")}</p>
      </section>

      <!-- Mailing volunteers is the paid plan
           (docs/design-paywall.md). A free roster keeps its page and its
           calendar, so the section is not here at all. -->
      {#if auth.participantMail}
        <section class="form-section">
          <label class="toggle-row" for="reminderToggle">
            <AppToggle bind:checked={reminderEnabled} inputId="reminderToggle" />
            <h2 class="section-heading">{t("chore.edit.reminderEnabled")}</h2>
          </label>
          <p class="muted section-explainer">{t("chore.edit.remindersExplainer")}</p>

          {#if reminderEnabled}
            <div class="field">
              <span class="field-label">{t("chore.edit.reminderDaysBefore")}</span>
              <NumberStepper
                bind:value={reminderDaysBefore}
                min={0}
                max={14}
                ariaLabel={t("chore.edit.reminderDaysBefore")}
              />
            </div>
          {/if}
        </section>
      {/if}

      <!-- How far ahead the schedule is pinned. A setting rather than
           part of the roster, so it belongs with the switches. -->
      <section class="form-section">
        <h2 class="section-heading">{t("chore.edit.commitHorizonDays")}</h2>
        <p class="muted section-explainer">{t("chore.edit.commitHorizonHint")}</p>
        <NumberStepper
          bind:value={commitHorizonDays}
          min={reminderEnabled ? reminderDaysBefore : 1}
          max={365}
          ariaLabel={t("chore.edit.commitHorizonDays")}
        />
      </section>
    </details>

    <section class="form-section">
      <h2 class="section-heading">{t("chore.edit.languageHeading")}</h2>
      <p class="muted section-explainer">{t("chore.edit.languageExplainer")}</p>
      <SelectField
        bind:value={rosterLocale}
        options={localeOptions}
        optionLabel="label"
        optionValue="value"
        fluid
      />
    </section>
  </FormPageShell>
{/if}

<style>
/* The shared form chrome lives in ``src/assets/forms.css``. Only the
 * roster's own rules are here. */
.stepper-row {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  flex-wrap: wrap;
}
.date-row {
  display: flex;
  gap: 1rem;
  flex-wrap: wrap;
}
.date-row .field {
  /* ``min-width: 0`` so both fields shrink to the same basis instead of
   * being sized by their placeholders, which are different lengths. */
  flex: 1 1 12rem;
  min-width: 0;
}
.chores-stack {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}
</style>

// frontend/src/pages/ChoresEditPage.vue
<script setup lang="ts">
import AppButton from "@/components/AppButton.vue";
import AppInput from "@/components/AppInput.vue";
import Select from "primevue/select";
import AppToggle from "@/components/AppToggle.vue";
import { computed, onMounted, ref, watch } from "vue";
import { useI18n } from "vue-i18n";
import { useRoute, useRouter } from "vue-router";
import AppCard from "@/components/AppCard.vue";
import AppHeader from "@/components/AppHeader.vue";
import ChoreEditor, { type ChoreDraft } from "@/components/ChoreEditor.vue";
import DatePicker from "@/components/DatePicker.vue";
import { DEFAULT_CHORE_EMOJI, firstUnusedEmoji } from "@/components/EmojiPicker.vue";
import FormPageShell from "@/components/FormPageShell.vue";
import ImageField from "@/components/ImageField.vue";
import NumberStepper from "@/components/NumberStepper.vue";
import RichTextField from "@/components/RichTextField.vue";
import { ApiError } from "@/api/client";
import type { ChoreIn, RosterCreate, RosterUpdate } from "@/api/types";
import StartAccountField from "@/components/StartAccountField.vue";
import StartedPanel from "@/components/StartedPanel.vue";
import { chapterList, useChapters } from "@/composables/useChapters";
import { useStartMode } from "@/composables/useStartMode";
import { useBilingualField } from "@/composables/useBilingualField";
import { useCreateRoster, useRoster, useUpdateRoster } from "@/composables/useChores";
import { useFormDraft } from "@/composables/useFormDraft";
import { useOrderedList } from "@/composables/useOrderedList";
import { useToasts } from "@/lib/toasts";
import { useAuthStore } from "@/stores/auth";

const props = defineProps<{ rosterId?: string }>();

const { t, locale } = useI18n();
const router = useRouter();
const route = useRoute();
const toasts = useToasts();
// The root's front door: see ``useStartMode``.
const {
  active: startActive,
  hasChapters,
  email: startEmail,
  started,
  validate: validateStartEmail,
  submit: submitStart,
  chapterFor,
  cancel: cancelStart,
} = useStartMode("roster");
const chaptersQuery = useChapters({ enabled: hasChapters });
const chapters = chapterList(chaptersQuery);
const auth = useAuthStore();
const createMutation = useCreateRoster();
const updateMutation = useUpdateRoster();

const isEdit = computed(() => Boolean(props.rosterId));

const chapterId = ref<string | null>(null);
const userChapterOptions = computed(() => {
  const memberIds = new Set((auth.user?.chapters ?? []).map((c) => c.id));
  return chapters.value.filter((c) => memberIds.has(c.id));
});

const nameNl = ref("");
const nameEn = ref("");
const descNl = ref("");
const descEn = ref("");
const { active: title, fallback: titleFallback } = useBilingualField(nameNl, nameEn);
const { active: body, fallback: bodyFallback } = useBilingualField(descNl, descEn);
const imageUrl = ref<string | null>(null);
const imageArtistInstagram = ref("");
const imageField = ref<InstanceType<typeof ImageField> | null>(null);
const rosterLocale = ref<"nl" | "en">((locale.value as "nl" | "en") ?? "nl");
const nameRequired = ref(false);
/* The switches live behind one fold, the same one every other edit page
 * ends with, and it starts closed every time. */
const advancedOpen = ref(false);
const periodWeeks = ref(1);
const startsOn = ref<Date | null>(null);
const endsOn = ref<Date | null>(null);
const reminderEnabled = ref(true);
// Rosters usually remind, so the switch starts on. Whether this
// account may is a separate question, and it is the one the payload
// asks: a free account has no reminder section on the form and sends
// no reminders (docs/design-paywall.md).
const sendsReminders = computed(() => reminderEnabled.value && auth.participantMail);
const reminderDaysBefore = ref(1);
const commitHorizonDays = ref(21);
const choreListState = useOrderedList<ChoreDraft>();
const chores = choreListState.items;
const submitting = ref(false);

const localeOptions = computed(() => [
  { value: "nl", label: t("chores.edit.localeNl") },
  { value: "en", label: t("chores.edit.localeEn") },
]);

// --- Date <-> "YYYY-MM-DD" (local, no UTC shift) --------------------
function isoDate(d: Date | null): string | null {
  if (!d) return null;
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}
function parseDate(s: string | null | undefined): Date | null {
  if (!s) return null;
  const [y, m, d] = s.split("-").map(Number);
  if (!y || !m || !d) return null;
  return new Date(y, m - 1, d);
}

const existingQuery = computed(() => (props.rosterId ? props.rosterId : ""));
const rosterQuery = isEdit.value ? useRoster(existingQuery) : null;

const notFound = computed(
  () =>
    isEdit.value &&
    rosterQuery?.error.value instanceof ApiError &&
    rosterQuery.error.value.status === 404,
);
const otherError = computed(() => isEdit.value && rosterQuery?.error.value && !notFound.value);

// Shrinking k drops now-out-of-range cycle slots, warning which chores
// lost days (the server clamps too — this keeps the UI honest).
watch(periodWeeks, (next, prev) => {
  if (next >= prev) return;
  const hi = 7 * next;
  const affected: string[] = [];
  for (const c of chores.value) {
    const kept = c.cycle_slots.filter((s) => s < hi);
    if (kept.length !== c.cycle_slots.length) {
      affected.push(c.name || t("chores.edit.untitledChore"));
      c.cycle_slots = kept;
    }
  }
  if (affected.length) {
    toasts.warn(t("chores.edit.slotsCleared", { names: affected.join(", ") }));
  }
});

onMounted(() => {
  if (isEdit.value) return;
  const queryChapter = (route.query.chapter as string | undefined) ?? null;
  const memberIds = new Set((auth.user?.chapters ?? []).map((c) => c.id));
  if (queryChapter && memberIds.has(queryChapter)) {
    chapterId.value = queryChapter;
  } else if (auth.user?.chapters?.length === 1) {
    chapterId.value = auth.user.chapters[0].id;
  }
  restoreDraftOnce();
});

// The data watch is ``immediate`` and can fire synchronously during setup
// when the roster is already in the Query cache (warm navigation). The draft
// helpers below aren't initialised yet at that point, so gate the draft
// restore on this flag and run it once explicitly after they're defined.
let draftReady = false;

watch(
  () => rosterQuery?.data.value,
  (existing) => {
    if (!existing) return;
    nameNl.value = existing.name_nl ?? "";
    nameEn.value = existing.name_en ?? "";
    descNl.value = existing.description_nl ?? "";
    descEn.value = existing.description_en ?? "";
    imageUrl.value = existing.image_url ?? null;
    imageArtistInstagram.value = existing.image_artist_instagram ?? "";
    rosterLocale.value = existing.locale;
    nameRequired.value = existing.name_required;
    chapterId.value = existing.chapter_id;
    periodWeeks.value = existing.period_weeks;
    startsOn.value = parseDate(existing.starts_on);
    endsOn.value = parseDate(existing.ends_on);
    reminderEnabled.value = existing.reminder_enabled;
    reminderDaysBefore.value = existing.reminder_days_before;
    commitHorizonDays.value = existing.commit_horizon_days;
    chores.value = (existing.chores ?? []).map((c) => ({
      id: c.id,
      name: c.name,
      description: c.description ?? null,
      cycle_slots: [...c.cycle_slots],
      people_per_shift: c.people_per_shift,
      emoji: c.emoji ?? DEFAULT_CHORE_EMOJI,
    }));
    if (draftReady) restoreDraftOnce();
  },
  { immediate: true },
);

// --- Draft persistence (dates stored as ISO strings) ---------------
const draftKey = computed(() => `chore-edit-draft:${props.rosterId ?? "new"}`);

interface RosterEditDraft {
  nameNl: string;
  nameEn: string;
  descNl: string;
  descEn: string;
  imageArtistInstagram: string;
  chapterId: string | null;
  rosterLocale: "nl" | "en";
  periodWeeks: number;
  startsOn: string | null;
  endsOn: string | null;
  reminderEnabled: boolean;
  reminderDaysBefore: number;
  commitHorizonDays: number;
  chores: ChoreDraft[];
}

function snapshot(): RosterEditDraft {
  return {
    nameNl: nameNl.value,
    nameEn: nameEn.value,
    descNl: descNl.value,
    descEn: descEn.value,
    imageArtistInstagram: imageArtistInstagram.value,
    chapterId: chapterId.value,
    rosterLocale: rosterLocale.value,
    periodWeeks: periodWeeks.value,
    startsOn: isoDate(startsOn.value),
    endsOn: isoDate(endsOn.value),
    reminderEnabled: reminderEnabled.value,
    reminderDaysBefore: reminderDaysBefore.value,
    commitHorizonDays: commitHorizonDays.value,
    chores: chores.value,
  };
}

function applyDraft(d: RosterEditDraft): void {
  nameNl.value = d.nameNl ?? "";
  nameEn.value = d.nameEn ?? "";
  descNl.value = d.descNl ?? "";
  descEn.value = d.descEn ?? "";
  imageArtistInstagram.value = d.imageArtistInstagram ?? "";
  chapterId.value = d.chapterId ?? null;
  rosterLocale.value = d.rosterLocale ?? "nl";
  periodWeeks.value = d.periodWeeks ?? 1;
  startsOn.value = parseDate(d.startsOn);
  endsOn.value = parseDate(d.endsOn);
  reminderEnabled.value = d.reminderEnabled ?? true;
  reminderDaysBefore.value = d.reminderDaysBefore ?? 1;
  commitHorizonDays.value = d.commitHorizonDays ?? 21;
  chores.value = (d.chores ?? []).map((c) => ({
    ...c,
    cycle_slots: [...(c.cycle_slots ?? [])],
    emoji: c.emoji ?? DEFAULT_CHORE_EMOJI,
  }));
}

const { loadDraft, clearDraft } = useFormDraft<RosterEditDraft>({
  key: draftKey,
  snapshot,
  apply: applyDraft,
  sources: [
    nameNl,
    nameEn,
    descNl,
    descEn,
    imageArtistInstagram,
    chapterId,
    rosterLocale,
    periodWeeks,
    startsOn,
    endsOn,
    reminderEnabled,
    reminderDaysBefore,
    commitHorizonDays,
    chores,
  ],
});

let draftRestored = false;
function restoreDraftOnce(): void {
  if (draftRestored) return;
  draftRestored = true;
  const draft = loadDraft();
  if (draft) applyDraft(draft);
}

// The draft helpers exist now — apply any value the immediate watch above
// already loaded from a warm cache (it skipped the restore back then).
draftReady = true;
if (rosterQuery?.data.value) restoreDraftOnce();

// --- Chore list helpers --------------------------------------------
function addChore(): void {
  choreListState.add({
    id: null,
    name: "",
    description: null,
    cycle_slots: [],
    people_per_shift: 1,
    // Start a new chore on an emoji no existing chore already uses.
    emoji: firstUnusedEmoji(chores.value.map((c) => c.emoji)),
  });
}
function removeChore(index: number): void {
  choreListState.removeAt(index);
}
function moveChore(index: number, delta: -1 | 1): void {
  choreListState.move(index, delta);
}
function setChore(index: number, next: ChoreDraft): void {
  const prev = chores.value[index];
  // Keep emojis unique: picking one another chore already uses swaps them,
  // handing that chore this chore's previous emoji.
  if (next.emoji !== prev.emoji) {
    const clash = chores.value.findIndex((c, i) => i !== index && c.emoji === next.emoji);
    if (clash !== -1) {
      choreListState.replaceAt(clash, { ...chores.value[clash], emoji: prev.emoji });
    }
  }
  choreListState.replaceAt(index, next);
}


// --- Cancel / submit -----------------------------------------------
function cancel(): void {
  clearDraft();
  if (cancelStart()) return;
  if (isEdit.value && props.rosterId) {
    void router.push(`/chores/${props.rosterId}/details`);
  } else {
    void router.push("/chores");
  }
}

async function submit() {
  // The backend requires the title in the primary language (``rosterLocale``);
  // the other language is an optional translation.
  const primaryName = (rosterLocale.value === "en" ? nameEn.value : nameNl.value).trim();
  if (!primaryName) {
    toasts.warn(t("chores.edit.fillName"));
    return;
  }
  if (hasChapters.value && !chapterId.value) {
    toasts.warn(t("chores.edit.fillChapter"));
    return;
  }
  if (startActive.value && !validateStartEmail()) return;
  if (!startsOn.value) {
    toasts.warn(t("chores.edit.fillStartsOn"));
    return;
  }
  if (chores.value.some((c) => !c.name.trim())) {
    toasts.warn(t("chores.edit.fillChoreName"));
    return;
  }
  submitting.value = true;
  try {
    const wirePayload: RosterCreate | RosterUpdate = {
      chapter_id: chapterFor(chapterId.value),
      name_nl: nameNl.value.trim() || null,
      name_en: nameEn.value.trim() || null,
      description_nl: descNl.value.trim() || null,
      description_en: descEn.value.trim() || null,
      image_artist_instagram: imageArtistInstagram.value.trim() || null,
      locale: rosterLocale.value,
      location: null,
      latitude: null,
      longitude: null,
      period_weeks: periodWeeks.value,
      starts_on: isoDate(startsOn.value) as string,
      ends_on: isoDate(endsOn.value),
      name_required: nameRequired.value,
      reminder_enabled: sendsReminders.value,
      reminder_days_before: reminderDaysBefore.value,
      commit_horizon_days: commitHorizonDays.value,
      chores: chores.value.map(
        (c): ChoreIn => ({
          id: c.id,
          name: c.name.trim(),
          description: c.description,
          cycle_slots: c.cycle_slots,
          people_per_shift: c.people_per_shift,
          emoji: c.emoji,
        }),
      ),
    };
    if (startActive.value) {
      // No session: the public link the response carries is the whole
      // result, and there is no details page to land on. A refusal has
      // already been explained; the draft stays so it can be retried.
      if (await submitStart(wirePayload)) clearDraft();
      return;
    }
    const result =
      isEdit.value && props.rosterId
        ? await updateMutation.mutateAsync({ id: props.rosterId, payload: wirePayload })
        : await createMutation.mutateAsync(wirePayload);
    await imageField.value?.flushPendingUpload(result.id);
    clearDraft();
    void router.push(`/chores/${result.id}/details`);
  } catch {
    toasts.error(t("chores.edit.saveFailed"));
  } finally {
    submitting.value = false;
  }
}
</script>

<template>
  <template v-if="notFound">
    <AppHeader />
    <div class="container-wide stack">
      <AppCard>
        <h2>{{ t("chores.edit.notFoundTitle") }}</h2>
        <p class="muted">{{ t("chores.edit.notFoundBody") }}</p>
        <router-link to="/chores" class="back-link">{{ t("chores.edit.backToList") }}</router-link>
      </AppCard>
    </div>
  </template>

  <template v-else-if="otherError">
    <AppHeader />
    <div class="container-wide stack">
      <AppCard>
        <p>{{ t("chores.edit.loadFailed") }}</p>
      </AppCard>
    </div>
  </template>

  <StartedPanel v-else-if="started" :started="started" :email="startEmail" />

  <FormPageShell
    v-else
    :title="isEdit ? t('chores.edit.editTitle') : t('chores.edit.newTitle')"
    :submit-label="isEdit ? t('chores.edit.save') : t('chores.edit.create')"
    :submitting="submitting"
    @submit="submit"
    @cancel="cancel"
  >
    <!-- Basics -->
    <section class="form-section">
      <StartAccountField v-if="startActive" v-model="startEmail" />
      <AppInput
        v-model="title"
        :placeholder="titleFallback || t('chores.edit.namePlaceholder')"
        fluid
      />
      <RichTextField
        v-model="body"
        :placeholder="t('chores.edit.descriptionPlaceholder')"
        :fallback-html="bodyFallback || null"
      />
      <Select
        v-if="hasChapters"
        v-model="chapterId"
        :options="userChapterOptions"
        option-label="name"
        option-value="id"
        :placeholder="t('chores.edit.chapterPlaceholder')"
        :disabled="userChapterOptions.length === 1 && chapterId !== null"
        fluid
      />
    </section>

    <!-- Uploading writes to the row it belongs to, which takes a
         session the visitor does not have yet. -->
    <ImageField
      v-if="!startActive"
      ref="imageField"
      resource="chores"
      :entity-id="props.rosterId ?? null"
      v-model:image-url="imageUrl"
      v-model:artist="imageArtistInstagram"
    />

    <!-- Recurrence + run window -->
    <section class="form-section">
      <h2 class="section-heading">{{ t("chores.edit.recurrenceHeading") }}</h2>
      <p class="muted section-explainer">{{ t("chores.edit.recurrenceExplainer") }}</p>

      <div class="stepper-row">
        <NumberStepper v-model="periodWeeks" :min="1" :max="8" :aria-label="t('chores.edit.periodWeeks')" />
      </div>

      <div class="date-row">
        <div class="field">
          <DatePicker
            v-model="startsOn"
            :locale="locale"
            date-format="dd-mm-yy"
            :placeholder="t('chores.edit.startDatePlaceholder')"
            fluid
          />
        </div>
        <div class="field">
          <DatePicker
            v-model="endsOn"
            :locale="locale"
            date-format="dd-mm-yy"
            show-button-bar
            :placeholder="t('chores.edit.endsOnPlaceholder')"
            fluid
          />
        </div>
      </div>

    </section>

    <!-- Chores -->
    <section class="form-section">
      <h2 class="section-heading">{{ t("chores.edit.choresHeading") }}</h2>
      <p class="muted section-explainer">{{ t("chores.edit.choresExplainer") }}</p>

      <div v-if="chores.length === 0" class="empty muted">
        {{ t("chores.edit.noChoresYet") }}
      </div>

      <div class="chores-stack">
        <ChoreEditor
          v-for="(c, idx) in chores"
          :key="c.id ?? `new-${idx}`"
          :model-value="c"
          :period-weeks="periodWeeks"
          :can-move-up="idx > 0"
          :can-move-down="idx < chores.length - 1"
          @update:model-value="(next) => setChore(idx, next)"
          @delete="removeChore(idx)"
          @move-up="moveChore(idx, -1)"
          @move-down="moveChore(idx, 1)"
        />
      </div>

      <AppButton
        type="button"
        :label="t('chores.edit.addChore')"
        icon="pi pi-plus"
        severity="secondary"
        @click="addChore"
      />
    </section>


    <!-- Every switch, folded away: above it is the thing itself, under
         it the page language. One fold on all six products. -->
    <details class="advanced" :open="advancedOpen" @toggle="advancedOpen = ($event.target as HTMLDetailsElement).open">
      <summary>{{ advancedOpen ? t("common.advancedHide") : t("common.advancedShow") }}</summary>

      <!-- Off by default: a name real or not is what the contract
           offers, so an empty box is an answer. A roster is the one
           place a nameless sign-up is hard to use, so this is the one
           an organiser is likeliest to switch on. -->
      <section class="form-section">
        <label class="toggle-row" for="nameRequiredToggle">
          <AppToggle v-model="nameRequired" inputId="nameRequiredToggle" />
          <h2 class="section-heading">{{ t("common.nameRequired") }}</h2>
        </label>
        <p class="muted section-explainer">{{ t("common.nameRequiredExplainer") }}</p>
      </section>

      <!-- Reminders. Mailing volunteers is the paid plan
           (docs/design-paywall.md); a free roster keeps the personal
           page and the month calendar, so the section is not here at
           all. -->
      <section v-if="auth.participantMail" class="form-section">
        <label class="toggle-row" for="reminderToggle">
          <AppToggle v-model="reminderEnabled" inputId="reminderToggle" />
          <h2 class="section-heading">{{ t("chores.edit.reminderEnabled") }}</h2>
        </label>
        <p class="muted section-explainer">{{ t("chores.edit.remindersExplainer") }}</p>

        <div v-if="reminderEnabled" class="field">
          <span class="field-label">{{ t("chores.edit.reminderDaysBefore") }}</span>
          <NumberStepper
            v-model="reminderDaysBefore"
            :min="0"
            :max="14"
            :aria-label="t('chores.edit.reminderDaysBefore')"
          />
        </div>
      </section>

      <!-- How far ahead the schedule is pinned. A setting rather than
           part of the roster, so it belongs in here with the switches
           rather than in a fold of its own inside the dates. -->
      <section class="form-section">
        <h2 class="section-heading">{{ t("chores.edit.commitHorizonDays") }}</h2>
        <p class="muted section-explainer">{{ t("chores.edit.commitHorizonHint") }}</p>
        <NumberStepper
          v-model="commitHorizonDays"
          :min="reminderEnabled ? reminderDaysBefore : 1"
          :max="365"
          :aria-label="t('chores.edit.commitHorizonDays')"
        />
      </section>
    </details>

    <!-- Language -->
    <section class="form-section">
      <h2 class="section-heading">{{ t("chores.edit.languageHeading") }}</h2>
      <p class="muted section-explainer">{{ t("chores.edit.languageExplainer") }}</p>
      <Select
        v-model="rosterLocale"
        :options="localeOptions"
        option-label="label"
        option-value="value"
        fluid
      />
    </section>
  </FormPageShell>
</template>

<style scoped>
/* Shared form chrome (.form-section, .section-heading, .section-explainer,
 * .toggle-row, .field, .field-label) lives in
 * ``src/assets/forms.css``. Only chore-specific rules stay here. */
.stepper-row {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  flex-wrap: wrap;
}
.date-row {
  display: flex;
  gap: 1rem;
  flex-wrap: wrap;
}
.date-row .field {
  /* min-width: 0 so both fields shrink to the equal flex-basis instead of
   * being sized by their (unequal-length) placeholder text. */
  flex: 1 1 12rem;
  min-width: 0;
}
.field-error {
  margin: 0;
  color: var(--brand-red);
  font-size: 0.8125rem;
}
.chores-stack {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}
</style>
