// frontend/src/pages/DatepollListPage.vue
<script setup lang="ts">
import { useQueryClient } from "@tanstack/vue-query";
import AppButton from "@/components/AppButton.vue";
import { computed, watch } from "vue";
import { useI18n } from "@/i18n";
import { useLocalizedText } from "@/composables/useLocalizedText";
import AppCard from "@/components/AppCard.vue";
import AppHeader from "@/components/AppHeader.vue";
import EntityCard from "@/components/EntityCard.vue";
import ListPageView from "@/components/ListPageView.vue";
import { get } from "@/api/client";
import { useChapterUrlFilter } from "@/composables/useChapterUrlFilter";
import { useDatepollClipboard } from "@/composables/useDatepollClipboard";
import {
  type DatepollListOut,
  datepollList,
  useArchiveDatepoll,
  useDatepollList,
} from "@/composables/useDatepolls";
import { useConfirms } from "@/lib/confirms";
import { datepollQrUrl, publicDatepollUrl } from "@/lib/datepoll-urls";
import { formatDate } from "@/lib/format";
import { useToasts } from "@/lib/toasts";
import { useAuthStore } from "@/stores/auth";

const { t, locale } = useI18n();
const lt = useLocalizedText();
const auth = useAuthStore();
const toasts = useToasts();
const confirms = useConfirms();
const qc = useQueryClient();
const { copyLink, copyQr } = useDatepollClipboard();

const { chapterFilter, setChapterFilter, chapterOptions } = useChapterUrlFilter();

const pollsQuery = useDatepollList({
  enabled: computed(() => auth.isApproved),
  chapterId: chapterFilter,
});
const polls = datepollList(pollsQuery);
const archiveMutation = useArchiveDatepoll();


watch(pollsQuery.isError, (isError) => {
  if (isError) toasts.error(t("datepoll.list.loadFailed"));
});

const loaded = computed(() => !auth.isApproved || !pollsQuery.isPending.value);

const sortedPolls = computed(() =>
  [...polls.value].sort((a, b) => b.created_at.localeCompare(a.created_at)),
);

function dateRange(p: DatepollListOut): string {
  if (p.date_count === 0) return t("datepoll.list.noDates");
  const count = t("datepoll.list.dateCount", { n: p.date_count });
  if (!p.first_date) return count;
  const first = formatDate(p.first_date, locale.value);
  if (!p.last_date || p.last_date === p.first_date) return `${count} · ${first}`;
  return `${count} · ${first} – ${formatDate(p.last_date, locale.value)}`;
}

const prefetched = new Set<string>();
function prefetchDetails(datepollId: string) {
  if (prefetched.has(datepollId)) return;
  prefetched.add(datepollId);
  void qc.prefetchQuery({
    queryKey: ["datepoll", "single", datepollId],
    queryFn: () => get(`/api/v1/datepoll/${datepollId}`),
  });
  void qc.prefetchQuery({
    queryKey: ["datepoll", datepollId, "summary"],
    queryFn: () => get(`/api/v1/datepoll/${datepollId}/summary`),
  });
}

function askArchive(p: DatepollListOut) {
  confirms.ask({
    header: t("datepoll.list.archiveConfirmTitle"),
    message: t("datepoll.list.archiveConfirmBody", { name: lt(p.name_nl, p.name_en) ?? "" }),
    icon: "exclamation-triangle",
    rejectLabel: t("common.cancel"),
    acceptLabel: t("datepoll.list.archive"),
    accept: async () => {
      try {
        await archiveMutation.mutateAsync(p.id);
        toasts.success(t("datepoll.list.archived"));
      } catch {
        toasts.error(t("datepoll.list.archiveFail"));
      }
    },
  });
}
</script>

<template>
  <template v-if="auth.needsChapters">
    <AppHeader />
    <div class="container-wide stack">
      <h1>{{ t("datepoll.list.title") }}</h1>
      <p class="muted">{{ t("datepoll.list.intro") }}</p>
      <AppCard>
        <h2>{{ t("dashboard.noChaptersTitle") }}</h2>
        <p class="muted">{{ t("dashboard.noChaptersBody") }}</p>
      </AppCard>
    </div>
  </template>

  <ListPageView
    v-else
    :title="t('datepoll.list.title')"
    :intro="t('datepoll.list.intro')"
    :items="sortedPolls"
    :loaded="loaded"
    :chapter-filter="chapterFilter"
    :chapter-options="chapterOptions"
    :search-placeholder="t('datepoll.list.searchPlaceholder')"
    :search-keys="(p: DatepollListOut) => [lt(p.name_nl, p.name_en) ?? '']"
    :empty-copy="t('datepoll.list.empty')"
    :no-matches-copy="t('datepoll.list.noMatches')"
    :skeleton-rows="2"
    @update:chapter-filter="setChapterFilter"
  >
    <template #actions-leading>
      <router-link
        :to="{
          path: '/datepoll/new',
          query: chapterFilter ? { chapter: chapterFilter } : undefined,
        }"
      >
        <AppButton :label="t('datepoll.list.newDatepoll')" icon="plus" />
      </router-link>
    </template>

    <template #row="{ item: p }">
      <EntityCard
        :public-url="publicDatepollUrl(p.slug)"
        :qr-src="datepollQrUrl(p.slug)"
        :copy-link-label="t('datepoll.share.copyLink')"
        :qr-label="t('datepoll.share.copyQr')"
        @mouseenter="prefetchDetails(p.id)"
        @focusin="prefetchDetails(p.id)"
        @copy-link="copyLink(p.slug)"
        @copy-qr="copyQr(p.slug)"
      >
        <template #title>
          <h3>
            {{ lt(p.name_nl, p.name_en) }}
            <span v-if="p.chapter_name" class="chapter-chip">{{ p.chapter_name }}</span>
          </h3>
        </template>

        <template #meta>
          <p class="muted">{{ dateRange(p) }}</p>
        </template>


        <template #actions>
          <router-link :to="`/datepoll/${p.id}/details`">
            <AppButton :label="t('datepoll.list.details')" icon="info-circle" size="small" severity="secondary" />
          </router-link>
          <AppButton
            :label="t('datepoll.list.archive')"
            icon="archive"
            size="small"
            severity="secondary"
            text
            @click="askArchive(p)"
          />
        </template>

        <template #count>{{ t("datepoll.list.responseCount", { n: p.submission_count }) }}</template>
      </EntityCard>
    </template>
  </ListPageView>
</template>

// frontend/src/pages/DatepollListPage.svelte
<script lang="ts">
import EntityListPage from "@/components/EntityListPage.svelte";
import { entityList } from "@/composables/useEntityList.svelte";
import { datepolls, type DatepollListOut } from "@/composables/useDatepolls.svelte";
import { shareClipboard } from "@/composables/useShareClipboard.svelte";
import { locale, t } from "@/i18n.svelte";
import { get } from "@/api/client";
import { datepollQrUrl, publicDatepollUrl } from "@/lib/datepoll-urls";
import { formatDate } from "@/lib/format";
import { queryClient } from "@/lib/query-client";
import { auth } from "@/stores/auth.svelte";

const copy = (key: string, params?: Record<string, unknown>) => t(`datepoll.list.${key}`, params);
const archive = datepolls.archive();
const list = entityList<DatepollListOut>({ archive: archive.run, copy });
const query = datepolls.list({
  enabled: () => auth.isApproved,
  chapterId: () => list.chapter.value,
});
const share = shareClipboard({
  publicUrlFor: publicDatepollUrl,
  qrUrlFor: datepollQrUrl,
  copyPrefix: "datepoll.share",
});

const sorted = $derived(
  [...(query.data ?? [])].sort((a, b) => b.created_at.localeCompare(a.created_at)),
);

/** How many dates are on offer and when they run. A poll with one date
 *  says that date; a poll with none says so, because it is a poll that
 *  cannot be answered yet. */
function dateRange(p: DatepollListOut): string {
  if (p.date_count === 0) return t("datepoll.list.noDates");
  const count = t("datepoll.list.dateCount", { n: p.date_count });
  if (!p.first_date) return count;
  const first = formatDate(p.first_date, locale());
  if (!p.last_date || p.last_date === p.first_date) return `${count} · ${first}`;
  return `${count} · ${first} – ${formatDate(p.last_date, locale())}`;
}
</script>

<EntityListPage
  {copy}
  {list}
  items={sorted}
  loaded={!auth.isApproved || !query.isPending}
  isError={query.isError}
  newPath="/datepoll/new"
  newLabel={copy("newDatepoll")}
  detailsPath={(p) => `/datepoll/${p.id}/details`}
  publicUrl={(p) => publicDatepollUrl(p.slug)}
  qrSrc={(p) => datepollQrUrl(p.slug)}
  sharePrefix="datepoll.share"
  copyLink={(p) => void share.copyLink(p.slug)}
  copyQr={(p) => void share.copyQr(p.slug)}
  prefetch={(id) => {
    void queryClient.prefetchQuery({
      queryKey: ["datepoll", "single", id],
      queryFn: () => get(`/api/v1/datepoll/${id}`),
    });
    void queryClient.prefetchQuery({
      queryKey: ["datepoll", id, "summary"],
      queryFn: () => get(`/api/v1/datepoll/${id}/summary`),
    });
  }}
>
  {#snippet meta(p: DatepollListOut)}
    <p class="muted">{dateRange(p)}</p>
  {/snippet}
  {#snippet count(p: DatepollListOut)}
    {t("datepoll.list.responseCount", { n: p.submission_count })}
  {/snippet}
</EntityListPage>
