// frontend/src/pages/FeedbackPage.svelte
<script lang="ts">
import AppButton from "@/components/AppButton.svelte";
import AppCard from "@/components/AppCard.svelte";
import AppTextarea from "@/components/AppTextarea.svelte";
import PublicHeader from "@/components/PublicHeader.svelte";
import RatingScale from "@/components/RatingScale.svelte";
import {
  type FeedbackQuestion,
  feedbackFormQuery,
  feedbackPreviewQuery,
  submitFeedback,
} from "@/composables/useFeedback.svelte";
import { setLocale, t } from "@/i18n.svelte";
import { ApiError } from "@/api/client";
import { route } from "@/router/navigation.svelte";
import { useToasts } from "@/lib/toasts";

/**
 * The day-after form, opened from the one email the app sends a
 * participant.
 *
 * The token in the URL is the whole of the visitor's identity here, and
 * spending it deletes it. ``preview`` is the organiser looking at their
 * own form: the same page, read-only, so what they check is what will
 * be sent.
 */
const { slug }: { slug: string } = $props();

const toasts = useToasts();
const token = (route.query.get("t") ?? "") as string;
const isPreview = token === "preview";

const formQuery = feedbackFormQuery(
  () => token,
  () => !isPreview && Boolean(token),
);
const previewQuery = feedbackPreviewQuery(
  () => slug,
  () => isPreview,
);
const submit = submitFeedback();

const form = $derived((isPreview ? previewQuery.data : formQuery.data) ?? null);

let ratings = $state<Record<string, number | null>>({});
let texts = $state<Record<string, string>>({});
let submitted = $state(false);

const error = $derived.by(() => {
  if (!token) return t("feedback.expired");
  const err = isPreview ? previewQuery.error : formQuery.error;
  if (!err) return null;
  return err instanceof ApiError && (err.status === 410 || err.status === 404)
    ? t("feedback.expired")
    : t("feedback.loadFailed");
});

// The form arrives in the event's language, and the page follows it: a
// participant reads the words the organiser wrote, not the words this
// browser prefers.
let seeded: unknown = undefined;
$effect(() => {
  const f = form;
  if (!f || f === seeded) return;
  seeded = f;
  setLocale(f.event_locale);
  for (const q of f.questions) {
    if (q.kind === "rating") ratings[q.key] = null;
    if (q.kind === "text") texts[q.key] = "";
  }
});

function prompt(q: FeedbackQuestion): string {
  return t(`feedback.questions.${q.key}.prompt`);
}

function ratingLabel(q: FeedbackQuestion, end: "Low" | "High"): string {
  return t(`feedback.questions.${q.key}.label${end}`);
}

async function send(event: Event): Promise<void> {
  event.preventDefault();
  if (!form || isPreview) return;
  // The same required check the server makes, so an unanswered
  // question is named here rather than coming back as a 422.
  for (const q of form.questions) {
    if (!q.required) continue;
    if (q.kind === "rating" && ratings[q.key] == null) {
      toasts.warn(prompt(q));
      return;
    }
    if (q.kind === "text" && !texts[q.key].trim()) {
      toasts.warn(prompt(q));
      return;
    }
  }

  const answers = form.questions.map((q) =>
    q.kind === "rating"
      ? { question_key: q.key, answer_int: ratings[q.key] }
      : { question_key: q.key, answer_text: texts[q.key] || null },
  );

  try {
    await submit.run({ token, answers });
    submitted = true;
  } catch (e) {
    toasts.error(
      e instanceof ApiError && (e.status === 410 || e.status === 404)
        ? t("feedback.expired")
        : t("feedback.submitFail"),
    );
  }
}
</script>

<div class="container stack">
  <PublicHeader />

  <!-- ``submitted`` beats ``error``: once a submit lands, nothing
       downstream may flip the visitor back to "this link is no longer
       valid". -->
  {#if submitted}
    <AppCard>
      <h2>{t("feedback.thanks")}</h2>
      <p class="muted">{t("feedback.thanksBody")}</p>
    </AppCard>
  {:else if error}
    <AppCard stack={false}>
      <p>{error}</p>
    </AppCard>
  {:else if !form}
    <AppCard stack={false}>
      <p class="muted">{t("common.loading")}</p>
    </AppCard>
  {:else}
    {#if isPreview}
      <AppCard stack={false} class="preview-banner">
        <p>{t("feedback.previewBanner")}</p>
      </AppCard>
    {/if}

    <AppCard>
      <h1>{t("feedback.title", { name: form.event_name })}</h1>
      <p class="muted intro">{t("feedback.intro")}</p>
    </AppCard>

    <form class="stack" novalidate onsubmit={send}>
      {#each form.questions as q (q.key)}
        <AppCard>
          <span class="prompt">{prompt(q)}</span>
          {#if q.kind === "rating"}
            <RatingScale
              bind:value={ratings[q.key]}
              labelLow={ratingLabel(q, "Low")}
              labelHigh={ratingLabel(q, "High")}
            />
          {:else}
            <AppTextarea
              bind:value={texts[q.key]}
              placeholder={t(`feedback.questions.${q.key}.placeholder`)}
              maxlength={500}
              rows={3}
              autoResize
              fluid
            />
          {/if}
        </AppCard>
      {/each}
      <div class="submit-row">
        <AppButton
          type="submit"
          label={t("feedback.submit")}
          loading={submit.pending}
          disabled={isPreview}
        />
      </div>
    </form>
  {/if}
</div>

<style>
.intro {
  font-size: 0.875rem;
}
.prompt {
  font-weight: 600;
  font-size: 1.125rem;
  line-height: 1.4;
}
div :global(.preview-banner) {
  border: 1px dashed var(--brand-red);
  background: color-mix(in srgb, var(--brand-red) 6%, transparent);
}
div :global(.preview-banner p) {
  margin: 0;
  font-size: 0.875rem;
  color: var(--brand-red);
}
/* Submit aligned right, matching the public sign-up form. */
.submit-row {
  display: flex;
  justify-content: flex-end;
}
</style>

// frontend/src/pages/FeedbackPage.vue
<script setup lang="ts">
import AppButton from "@/components/AppButton.vue";
import AppTextarea from "@/components/AppTextarea.vue";
import { computed, ref, watch } from "vue";
import { useI18n } from "@/i18n";
import { useRoute } from "vue-router";
import AppCard from "@/components/AppCard.vue";
import PublicHeader from "@/components/PublicHeader.vue";
import RatingScale from "@/components/RatingScale.vue";
import { ApiError } from "@/api/client";
import {
  type FeedbackQuestion,
  useFeedbackForm,
  useFeedbackPreview,
  useSubmitFeedback,
} from "@/composables/useFeedback";
import { useToasts } from "@/lib/toasts";

const props = defineProps<{ slug: string }>();

const { t, locale } = useI18n();
const route = useRoute();
const toasts = useToasts();

const ratings = ref<Record<string, number | null>>({});
const texts = ref<Record<string, string>>({});
const submitted = ref(false);

const token = (route.query.t as string | undefined) ?? "";
const isPreview = token === "preview";

const formQuery = useFeedbackForm(token, !isPreview && Boolean(token));
const previewQuery = useFeedbackPreview(
  computed(() => props.slug),
  isPreview,
);
const submitMutation = useSubmitFeedback();

const form = computed(() =>
  isPreview ? previewQuery.data.value ?? null : formQuery.data.value ?? null,
);
const submitting = computed(() => submitMutation.isPending.value);

const error = computed<string | null>(() => {
  if (!token) return t("feedback.expired");
  const err = isPreview ? previewQuery.error.value : formQuery.error.value;
  if (!err) return null;
  return err instanceof ApiError && (err.status === 410 || err.status === 404)
    ? t("feedback.expired")
    : t("feedback.loadFailed");
});

watch(
  form,
  (f) => {
    if (!f) return;
    locale.value = f.event_locale;
    for (const q of f.questions) {
      if (q.kind === "rating") ratings.value[q.key] = null;
      if (q.kind === "text") texts.value[q.key] = "";
    }
  },
  { immediate: true },
);

function questionPrompt(q: FeedbackQuestion): string {
  return t(`feedback.questions.${q.key}.prompt`);
}

function ratingLabel(q: FeedbackQuestion, end: "Low" | "High"): string {
  return t(`feedback.questions.${q.key}.label${end}`);
}

function textPlaceholder(q: FeedbackQuestion): string {
  return t(`feedback.questions.${q.key}.placeholder`);
}

async function submit() {
  if (!form.value || isPreview) return;
  // Client-side check on required questions, mirrors backend.
  for (const q of form.value.questions) {
    if (!q.required) continue;
    if (q.kind === "rating" && ratings.value[q.key] == null) {
      toasts.warn(questionPrompt(q));
      return;
    }
    if (q.kind === "text" && !texts.value[q.key].trim()) {
      toasts.warn(questionPrompt(q));
      return;
    }
  }

  const answers = form.value.questions.map((q) =>
    q.kind === "rating"
      ? { question_key: q.key, answer_int: ratings.value[q.key] }
      : { question_key: q.key, answer_text: texts.value[q.key] || null },
  );

  try {
    await submitMutation.mutateAsync({ token, answers });
    submitted.value = true;
  } catch (e) {
    const msg =
      e instanceof ApiError && (e.status === 410 || e.status === 404)
        ? t("feedback.expired")
        : t("feedback.submitFail");
    toasts.error(msg);
  }
}
</script>

<template>
  <div class="container stack">
    <PublicHeader />

    <!-- ``submitted`` beats ``error``: once a submit lands, no
         downstream refetch should be able to flip the visitor
         back to a "link no longer valid" message. -->
    <AppCard v-if="submitted">
      <h2>{{ t("feedback.thanks") }}</h2>
      <p class="muted">{{ t("feedback.thanksBody") }}</p>
    </AppCard>

    <AppCard v-else-if="error" :stack="false">
      <p>{{ error }}</p>
    </AppCard>

    <AppCard v-else-if="!form" :stack="false">
      <p class="muted">{{ t("common.loading") }}</p>
    </AppCard>

    <template v-else>
      <AppCard v-if="isPreview" :stack="false" class="preview-banner">
        <p>{{ t("feedback.previewBanner") }}</p>
      </AppCard>

      <AppCard>
        <h1>{{ t("feedback.title", { name: form.event_name }) }}</h1>
        <p class="muted intro">{{ t("feedback.intro") }}</p>
      </AppCard>

      <form class="stack" novalidate @submit.prevent="submit">
        <AppCard v-for="q in form.questions" :key="q.key">
          <label class="prompt">
            {{ questionPrompt(q) }}
          </label>
          <RatingScale
            v-if="q.kind === 'rating'"
            :model-value="ratings[q.key]"
            :label-low="ratingLabel(q, 'Low')"
            :label-high="ratingLabel(q, 'High')"
            @update:model-value="ratings[q.key] = $event"
          />
          <AppTextarea
            v-else
            v-model="texts[q.key]"
            :placeholder="textPlaceholder(q)"
            :maxlength="500"
            :rows="3"
            auto-resize
            fluid
          />
        </AppCard>
        <div class="submit-row">
          <AppButton
            type="submit"
            :label="t('feedback.submit')"
            :loading="submitting"
            :disabled="isPreview"
          />
        </div>
      </form>
    </template>
  </div>
</template>

<style scoped>
.intro {
  font-size: 0.9375rem;
}
.prompt {
  font-weight: 600;
  font-size: 1.0625rem;
  line-height: 1.4;
}
.preview-banner {
  border: 1px dashed var(--brand-red);
  background: color-mix(in srgb, var(--brand-red) 6%, transparent);
}
.preview-banner p {
  margin: 0;
  font-size: 0.9375rem;
  color: var(--brand-red);
}
/* Submit aligned right, matching the public sign-up form. */
.submit-row {
  display: flex;
  justify-content: flex-end;
}
</style>
