// frontend/src/pages/NotFoundPage.vue
<script setup lang="ts">
import { useI18n } from "vue-i18n";
import AppCard from "@/components/AppCard.vue";
import AppHeader from "@/components/AppHeader.vue";

const { t } = useI18n();
</script>

<template>
  <AppHeader />
  <div class="container-wide">
    <AppCard :stack="false">
      <h1>{{ t("notFound.title") }}</h1>
      <p>{{ t("notFound.body") }}</p>
      <router-link to="/">{{ t("notFound.back") }}</router-link>
    </AppCard>
  </div>
</template>

// frontend/src/pages/NotFoundPage.svelte
<script lang="ts">
import AppCard from "@/components/AppCard.svelte";
import AppHeader from "@/components/AppHeader.svelte";
import RouterLink from "@/router/RouterLink.svelte";
import { t } from "@/i18n.svelte";
</script>

<AppHeader />
<div class="container-wide">
  <AppCard stack={false}>
    <h1>{t("notFound.title")}</h1>
    <p>{t("notFound.body")}</p>
    <RouterLink to="/">{t("notFound.back")}</RouterLink>
  </AppCard>
</div>
