// frontend/src/pages/RedeemPage.svelte
<script lang="ts">
import AppCard from "@/components/AppCard.svelte";
import AppHeader from "@/components/AppHeader.svelte";
import RouterLink from "@/router/RouterLink.svelte";
import { t } from "@/i18n.svelte";
import { ApiError } from "@/api/client";
import { redeem } from "@/stores/auth.svelte";
import { go, route } from "@/router/navigation.svelte";

let error = $state<string | null>(null);

async function signIn() {
  const token = route.query.get("token") ?? "";
  if (!token) {
    error = t("auth.linkExpired");
    return;
  }
  try {
    await redeem(token);
    void go("/", { replace: true });
  } catch (e) {
    error =
      e instanceof ApiError && e.status === 410 ? t("auth.linkExpired") : t("auth.loginFailed");
  }
}
void signIn();
</script>

<AppHeader />
<div class="container-wide">
  {#if error}
    <AppCard>
      <h1>{t("auth.linkExpiredTitle")}</h1>
      <p class="muted">{error}</p>
      <p><RouterLink to="/">{t("auth.requestNewLink")}</RouterLink></p>
    </AppCard>
  {:else}
    <AppCard>
      <p class="muted">{t("auth.signingIn")}</p>
    </AppCard>
  {/if}
</div>

// frontend/src/pages/RedeemPage.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";
import { useI18n } from "@/i18n";
import { useRoute, useRouter } from "vue-router";
import AppCard from "@/components/AppCard.vue";
import AppHeader from "@/components/AppHeader.vue";
import { ApiError } from "@/api/client";
import { useAuthStore } from "@/stores/auth";

const { t } = useI18n();
const auth = useAuthStore();
const route = useRoute();
const router = useRouter();

const error = ref<string | null>(null);

onMounted(async () => {
  const token = (route.query.token as string | undefined) ?? "";
  if (!token) {
    error.value = t("auth.linkExpired");
    return;
  }
  try {
    await auth.redeem(token);
    void router.replace("/");
  } catch (e) {
    error.value =
      e instanceof ApiError && e.status === 410
        ? t("auth.linkExpired")
        : t("auth.loginFailed");
  }
});
</script>

<template>
  <AppHeader />
  <div class="container-wide">
    <AppCard v-if="error">
      <h1>{{ t("auth.linkExpiredTitle") }}</h1>
      <p class="muted">{{ error }}</p>
      <p>
        <router-link to="/">{{ t("auth.requestNewLink") }}</router-link>
      </p>
    </AppCard>
    <AppCard v-else>
      <p class="muted">{{ t("auth.signingIn") }}</p>
    </AppCard>
  </div>
</template>
