// frontend/src/pages/RegisterCompletePage.vue
<script setup lang="ts">
import AppButton from "@/components/AppButton.vue";
import AppInput from "@/components/AppInput.vue";
import { onMounted, ref } from "vue";
import { useI18n } from "vue-i18n";
import { useRoute, useRouter } from "vue-router";
import { ApiError } from "@/api/client";
import AppCard from "@/components/AppCard.vue";
import AppHeader from "@/components/AppHeader.vue";
import { useToasts } from "@/lib/toasts";
import { useAuthStore } from "@/stores/auth";

const { t } = useI18n();
const auth = useAuthStore();
const route = useRoute();
const router = useRouter();
const toasts = useToasts();

const token = ref("");
const name = ref("");
const submitting = ref(false);
const linkInvalid = ref(false);

onMounted(() => {
  const raw = (route.query.token as string | undefined) ?? "";
  if (!raw) {
    linkInvalid.value = true;
    return;
  }
  token.value = raw;
});

async function submit() {
  const trimmed = name.value.trim();
  if (!trimmed) {
    toasts.warn(t("auth.fillName"));
    return;
  }
  submitting.value = true;
  try {
    await auth.completeRegistration(token.value, trimmed);
    void router.replace("/");
  } catch (e) {
    // 410 means the token was already used or expired between
    // page-load and submit — surface the same "link expired" card
    // the redeem flow uses, with a route back to the landing page.
    if (e instanceof ApiError && e.status === 410) {
      linkInvalid.value = true;
    } else {
      toasts.error(t("auth.completeFailed"));
    }
  } finally {
    submitting.value = false;
  }
}
</script>

<template>
  <AppHeader />
  <div class="container-wide">
    <AppCard v-if="linkInvalid">
      <h1>{{ t("auth.linkExpiredTitle") }}</h1>
      <p class="muted">{{ t("auth.linkExpired") }}</p>
      <p>
        <router-link to="/">{{ t("auth.requestNewLink") }}</router-link>
      </p>
    </AppCard>

    <AppCard v-else>
      <h1>{{ t("auth.completeTitle") }}</h1>
      <p class="muted">{{ t("auth.completeBody") }}</p>
      <form class="stack" method="post" action="" novalidate @submit.prevent="submit">
        <AppInput
          v-model="name"
          name="name"
          :placeholder="t('auth.name')"
          autocomplete="name"
          autofocus
          fluid
        />
        <AppButton type="submit" :label="t('auth.completeSubmit')" :loading="submitting" />
      </form>
    </AppCard>
  </div>
</template>

// frontend/src/pages/RegisterCompletePage.svelte
<script lang="ts">
import AppButton from "@/components/AppButton.svelte";
import AppCard from "@/components/AppCard.svelte";
import AppHeader from "@/components/AppHeader.svelte";
import AppInput from "@/components/AppInput.svelte";
import RouterLink from "@/router/RouterLink.svelte";
import { t } from "@/i18n.svelte";
import { ApiError } from "@/api/client";
import { useToasts } from "@/lib/toasts";
import { completeRegistration } from "@/stores/auth.svelte";
import { go, route } from "@/router/navigation.svelte";

const toasts = useToasts();

const token = route.query.get("token") ?? "";
let name = $state("");
let submitting = $state(false);
let linkInvalid = $state(!token);

async function submit() {
  const trimmed = name.trim();
  if (!trimmed) {
    toasts.warn(t("auth.fillName"));
    return;
  }
  submitting = true;
  try {
    await completeRegistration(token, trimmed);
    void go("/", { replace: true });
  } catch (e) {
    // 410 means the token was used or expired between the page load and
    // the submit: the same "link expired" card the redeem flow uses,
    // with a route back to the landing page.
    if (e instanceof ApiError && e.status === 410) linkInvalid = true;
    else toasts.error(t("auth.completeFailed"));
  } finally {
    submitting = false;
  }
}
</script>

<AppHeader />
<div class="container-wide">
  {#if linkInvalid}
    <AppCard>
      <h1>{t("auth.linkExpiredTitle")}</h1>
      <p class="muted">{t("auth.linkExpired")}</p>
      <p><RouterLink to="/">{t("auth.requestNewLink")}</RouterLink></p>
    </AppCard>
  {:else}
    <AppCard>
      <h1>{t("auth.completeTitle")}</h1>
      <p class="muted">{t("auth.completeBody")}</p>
      <form
        class="stack"
        method="post"
        action=""
        novalidate
        onsubmit={(e) => {
          e.preventDefault();
          void submit();
        }}
      >
        <AppInput
          bind:value={name}
          name="name"
          placeholder={t("auth.name")}
          autocomplete="name"
          autofocus
          fluid
        />
        <AppButton type="submit" label={t("auth.completeSubmit")} loading={submitting} />
      </form>
    </AppCard>
  {/if}
</div>
