// frontend/src/pages/UsersPage.vue
<script setup lang="ts">
import AppButton from "@/components/AppButton.vue";
import AppInput from "@/components/AppInput.vue";
import MultiSelectField from "@/components/MultiSelectField.vue";
import AppToggle from "@/components/AppToggle.vue";
import { computed, ref } from "vue";
import { useI18n } from "vue-i18n";
import AppCard from "@/components/AppCard.vue";
import AppDialog from "@/components/AppDialog.vue";
import AppHeader from "@/components/AppHeader.vue";
import AppSkeleton from "@/components/AppSkeleton.vue";
import SearchInput from "@/components/SearchInput.vue";
import {
  useApproveUser,
  useDemoteUser,
  usePromoteUser,
  useRemoveUser,
  useRenameUser,
  useSetUserChapters,
  userList,
  useUsers,
} from "@/composables/useAdmin";
import { type Chapter, chapterList, useChapters } from "@/composables/useChapters";
import { useGuardedMutation } from "@/composables/useGuardedMutation";
import { can as permCan } from "@/lib/permissions";
import { useToasts } from "@/lib/toasts";
import { type User, useAuthStore } from "@/stores/auth";

const { t } = useI18n();
const auth = useAuthStore();
const toasts = useToasts();

// Permission helpers — every UI affordance gates through these
// so the visible buttons match the matrix on the backend. The
// row-level helpers take the target ``User`` so self-service
// vs admin actions render correctly.
function canApprove(_target: User): boolean {
  return permCan(auth.user, "approve_user");
}
function canEdit(target: User): boolean {
  // Edit dialog covers rename + set-chapters; show the pencil
  // when the actor can do at least one of those.
  return (
    permCan(auth.user, "rename_user", target) ||
    permCan(auth.user, "set_user_chapters", target)
  );
}
function canDelete(target: User): boolean {
  return permCan(auth.user, "delete_user", target) && target.id !== auth.user?.id;
}
function canTogglePromotion(target: User): boolean {
  // The dialog's admin toggle is only useful when the actor can
  // both promote and demote (otherwise it's a one-way switch
  // they can't reverse). In practice that means: admin actor,
  // not editing self.
  return (
    permCan(auth.user, "promote_user", target) &&
    permCan(auth.user, "demote_user", target)
  );
}

const usersQuery = useUsers();
const users = userList(usersQuery);
const approveMutation = useApproveUser();
const setChaptersMutation = useSetUserChapters();
const promoteMutation = usePromoteUser();
const demoteMutation = useDemoteUser();
const removeMutation = useRemoveUser();
const renameMutation = useRenameUser();

const askDeleteUser = useGuardedMutation(removeMutation, (u: User) => ({
  vars: u.id,
  ok: t("admin.deleteUserOk", { name: u.name }),
  fail: t("admin.deleteUserFail"),
  confirm: {
    header: t("admin.deleteUserConfirmTitle"),
    message: t("admin.deleteUserConfirmBody", { name: u.name }),
    icon: "exclamation-triangle",
    rejectLabel: t("common.cancel"),
    acceptLabel: t("admin.deleteUser"),
  },
}));

// Chapters list — only the option pool for the user-edit dialog's
// MultiSelect. Chapter CRUD lives on /chapters.
const chaptersQuery = useChapters({ includeArchived: false });
const chapters = chapterList(chaptersQuery);

// --- User-edit dialog -------------------------------------------------
//
// One dialog covers every user-mutating flow on this page: approve a
// pending user, change an approved user's chapter, change a user's
// display name, promote/demote admin. The mode flag distinguishes
// "approve" (chapter required, fires /approve + sends the approval
// email) from "edit" (independent rename / assign-chapter /
// promote-or-demote calls fire only for fields that actually
// changed).
//
// The admin toggle is *deferred*: flipping it inside the dialog only
// stages the change. Nothing hits the backend until "Save".
type EditMode = "approve" | "edit";
const userEditOpen = ref(false);
const userEditMode = ref<EditMode>("approve");
const userEditTarget = ref<User | null>(null);
const userEditName = ref("");
const userEditChapters = ref<Chapter[]>([]);
const userEditIsAdmin = ref(false);
const userEditSubmitting = ref(false);

function chaptersForUser(u: User): Chapter[] {
  // Resolve via the chapters store so an upstream chapter rename
  // flows in reactively. Falls back to the cached projection for
  // chapters that have since been soft-deleted (which the live
  // ``chapters.value`` doesn't include).
  const live = new Map(chapters.value.map((c) => [c.id, c]));
  return u.chapters
    .map((ref) => live.get(ref.id) ?? (ref as unknown as Chapter))
    .sort((a, b) => a.name.localeCompare(b.name));
}

// --- User search -----------------------------------------------------
const userQuery = ref("");

// Sort tiers, top to bottom:
//   0  the actor's own row — most-likely target of any action
//   1  pending approval — admin's first task is clearing these
//   2  approved admins   — quick reach for promote / contact
//   3  approved organisers — the long tail
// Within each tier we fall through to newest-first by created_at,
// which keeps row order stable across renders for the same data.
function _tier(u: User, selfId: string | null): number {
  if (u.id === selfId) return 0;
  if (!u.is_approved) return 1;
  if (u.role === "admin") return 2;
  return 3;
}

const sortedUsers = computed(() => {
  const selfId = auth.user?.id ?? null;
  return [...users.value].sort((a, b) => {
    const tierDiff = _tier(a, selfId) - _tier(b, selfId);
    if (tierDiff !== 0) return tierDiff;
    return b.created_at.localeCompare(a.created_at);
  });
});

const filteredUsers = computed(() => {
  const q = userQuery.value.trim().toLowerCase();
  if (!q) return sortedUsers.value;
  return sortedUsers.value.filter((u) => {
    const chapterMatch = u.chapters.some((c) => c.name.toLowerCase().includes(q));
    return (
      u.name.toLowerCase().includes(q) ||
      u.email.toLowerCase().includes(q) ||
      chapterMatch
    );
  });
});

const loaded = computed(() => !usersQuery.isLoading.value);

function openApprove(u: User) {
  userEditMode.value = "approve";
  userEditTarget.value = u;
  userEditName.value = u.name;
  userEditChapters.value = [];
  // Approve always lands as a non-admin organiser; admin promotion
  // is a separate, post-approval action.
  userEditIsAdmin.value = false;
  userEditOpen.value = true;
}

function openEdit(u: User) {
  userEditMode.value = "edit";
  userEditTarget.value = u;
  userEditName.value = u.name;
  // Resolve to live ``Chapter`` rows from the chapters store so
  // the MultiSelect's selected-chip names update reactively when
  // an upstream chapter rename lands.
  const liveByRef = new Map(chapters.value.map((c) => [c.id, c]));
  userEditChapters.value = u.chapters
    .map((ref) => liveByRef.get(ref.id))
    .filter((c): c is Chapter => c !== undefined);
  userEditIsAdmin.value = u.role === "admin";
  userEditOpen.value = true;
}

function _setEquals(a: string[], b: string[]): boolean {
  if (a.length !== b.length) return false;
  const sb = new Set(b);
  return a.every((x) => sb.has(x));
}

async function submitUserEdit() {
  const target = userEditTarget.value;
  if (!target) return;

  const trimmedName = userEditName.value.trim();
  if (!trimmedName) {
    toasts.warn(t("admin.userEditFillName"));
    return;
  }

  // Chapters are required for *edit* mode (an approved user
  // shouldn't be able to clear themselves out of every
  // chapter), but optional in *approve* mode — the user can
  // self-pick via the dashboard's onboarding banner once they're
  // logged in.
  if (userEditMode.value === "edit" && userEditChapters.value.length === 0) {
    toasts.warn(t("admin.userEditPickChapter"));
    return;
  }

  const desiredChapterIds = userEditChapters.value.map((c) => c.id);
  const currentChapterIds = target.chapters.map((c) => c.id);

  userEditSubmitting.value = true;
  try {
    if (userEditMode.value === "approve") {
      // Rename first so the approval email carries the corrected
      // name. /approve doesn't accept a name field — keeping the
      // endpoints orthogonal means each one stays small + auditable.
      if (trimmedName !== target.name) {
        await renameMutation.mutateAsync({ userId: target.id, name: trimmedName });
      }
      await approveMutation.mutateAsync({
        userId: target.id,
        chapterIds: desiredChapterIds,
      });
      toasts.success(t("admin.approveOk"));
    } else {
      // Edit mode — fire only the endpoints whose field actually
      // changed. Three no-op clicks (open + Save with nothing
      // edited) close the dialog without a single round-trip.
      const renamed = trimmedName !== target.name;
      const chaptersChanged = !_setEquals(desiredChapterIds, currentChapterIds);
      const wasAdmin = target.role === "admin";
      const roleChanged = userEditIsAdmin.value !== wasAdmin;

      if (renamed) {
        await renameMutation.mutateAsync({ userId: target.id, name: trimmedName });
      }
      if (chaptersChanged) {
        await setChaptersMutation.mutateAsync({
          userId: target.id,
          chapterIds: desiredChapterIds,
        });
      }
      // Promote/demote last so a partial failure earlier doesn't
      // leave a user with elevated privileges they wouldn't have
      // had otherwise.
      if (roleChanged) {
        if (userEditIsAdmin.value) {
          await promoteMutation.mutateAsync(target.id);
        } else {
          await demoteMutation.mutateAsync(target.id);
        }
      }
      if (renamed || chaptersChanged || roleChanged) {
        toasts.success(t("admin.userEditOk"));
      }
    }
    userEditOpen.value = false;
  } catch {
    toasts.error(
      userEditMode.value === "approve"
        ? t("admin.approveFail")
        : t("admin.userEditFail"),
    );
  } finally {
    userEditSubmitting.value = false;
  }
}
</script>

<template>
  <AppHeader />
  <div class="container-wide stack">
    <h1>{{ t("admin.usersTitle") }}</h1>
    <p class="muted">{{ t("admin.usersIntro") }}</p>

    <AppCard>
      <AppSkeleton v-if="!loaded" :rows="4" />
      <template v-else>
        <SearchInput
          v-model="userQuery"
          :placeholder="t('admin.searchPlaceholder')"
        />
        <div v-if="users.length === 0">
          <p class="muted">{{ t("admin.empty") }}</p>
        </div>
        <p v-else-if="filteredUsers.length === 0" class="muted">
          {{ t("admin.noMatches") }}
        </p>
        <div v-for="u in filteredUsers" :key="u.id" class="account-row">
        <div class="account-main">
          <div class="account-identity">
            <strong>{{ u.name }}</strong>
            <span class="muted"> · {{ u.email }}</span>
            <span v-if="u.is_approved && u.role === 'admin'" class="admin-chip">{{ t("admin.adminToggle") }}</span>
          </div>
          <div class="account-actions">
            <AppButton
              v-if="!u.is_approved"
              :label="t('admin.approve')"
              size="small"
              :disabled="!canApprove(u)"
              @click="openApprove(u)"
            />
            <AppButton
              v-if="u.is_approved"
              icon="pencil"
              size="small"
              severity="secondary"
              text
              :disabled="!canEdit(u)"
              :aria-label="t('admin.userEditDialogTitle', { name: u.name })"
              @click="openEdit(u)"
            />
            <AppButton
              icon="trash"
              size="small"
              severity="secondary"
              text
              :disabled="!canDelete(u)"
              :aria-label="t('admin.deleteUser')"
              @click="askDeleteUser(u)"
            />
          </div>
        </div>
        <!-- Chapter chips on their own row beneath the
             identity. Wrapping is intentionally disabled and
             overflow is hidden; many-chapter members get the
             first few chips fully rendered with the row clipped
             at the right edge. The pencil-icon dialog is where
             you go to see the full set + edit. -->
        <div v-if="chaptersForUser(u).length > 0" class="account-chapters">
          <span
            v-for="c in chaptersForUser(u)"
            :key="c.id"
            class="chapter-chip"
          >{{ c.name }}</span>
        </div>
      </div>
      </template>
    </AppCard>

    <AppDialog
      v-model:visible="userEditOpen"
      :header="userEditMode === 'approve'
        ? t('admin.approveDialogTitle')
        : t('admin.userEditDialogTitle', { name: userEditTarget?.name ?? '' })"
    >
      <p class="muted dialog-text">
        {{
          userEditMode === "approve"
            ? t("admin.approveDialogBody", { name: userEditTarget?.name ?? "" })
            : t("admin.userEditDialogBody")
        }}
      </p>
      <label class="reassign-label">
        {{ t("auth.name") }}
        <AppInput
          v-model="userEditName"
          autocomplete="off"
          fluid
          @keydown.enter="submitUserEdit"
        />
      </label>
      <label class="reassign-label">
        {{ t("admin.chaptersLabel") }}
        <MultiSelectField
          v-model="userEditChapters"
          :options="chapters"
          option-label="name"
          :placeholder="t('admin.userEditPickChapter')"
          display="chip"
          filter
          fluid
        />
      </label>
      <!-- Admin toggle is deferred: flipping it stages a change
           that only commits when "Save" is clicked. Hidden in
           approve mode (a freshly approved user is never an admin
           on the same click; promotion is a separate, explicit
           step). Disabled when editing your own row — the server
           rejects self-demotion, and we want the UI to surface
           that constraint up front rather than 409 on submit. -->
      <label
        v-if="userEditMode === 'edit'"
        class="admin-toggle"
        :class="{ disabled: !userEditTarget || !canTogglePromotion(userEditTarget) }"
      >
        <AppToggle
          v-model="userEditIsAdmin"
          :disabled="!userEditTarget || !canTogglePromotion(userEditTarget)"
        />
        <span>{{ t("admin.adminToggle") }}</span>
      </label>
      <template #footer>
        <AppButton :label="t('common.cancel')" severity="secondary" text @click="userEditOpen = false" />
        <AppButton
          :label="userEditMode === 'approve' ? t('admin.approve') : t('common.save')"
          :disabled="
            !userEditName.trim() ||
            (userEditMode === 'edit' && userEditChapters.length === 0)
          "
          :loading="userEditSubmitting"
          @click="submitUserEdit"
        />
      </template>
    </AppDialog>
  </div>
</template>

<style scoped>
/* Mobile: the account-main row stays as identity-then-actions
 * (with chips below); the actions cluster aligns to the end of
 * the available width and the identity truncates if needed. */
@media (max-width: 540px) {
  .account-actions {
    margin-left: auto;
  }
}
/* Two-row account card: identity + admin chip + actions on the
 * top row, chapter chips clipped on a second row beneath. */
.account-row {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
  padding: 0.5rem 0.5rem;
  border-radius: 6px;
  transition: background 120ms ease;
}
.account-row:hover {
  background: var(--brand-surface-100);
}
.account-main {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 0.75rem;
  min-width: 0;
}
.account-identity {
  display: flex;
  align-items: baseline;
  gap: 0.5rem;
  min-width: 0;
  flex: 1;
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}
.account-identity > strong {
  flex-shrink: 0;
}
.account-actions {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  flex-shrink: 0;
}
.account-chapters {
  display: flex;
  flex-wrap: nowrap;
  gap: 0.375rem;
  overflow: hidden;
  white-space: nowrap;
  mask-image: linear-gradient(to right, black 85%, transparent 100%);
  -webkit-mask-image: linear-gradient(to right, black 85%, transparent 100%);
}
.account-chapters .chapter-chip {
  flex-shrink: 0;
}
.admin-chip {
  display: inline-flex;
  align-items: center;
  padding: 0.25rem 0.625rem;
  border-radius: 999px;
  background: color-mix(in srgb, var(--brand-red), transparent 90%);
  color: var(--brand-red);
  font-size: 0.875rem;
  font-weight: 600;
  white-space: nowrap;
}
.admin-toggle {
  display: inline-flex;
  align-items: center;
  gap: 0.375rem;
  font-size: 0.875rem;
  color: var(--brand-text-muted);
  cursor: pointer;
}
.admin-toggle.disabled {
  cursor: default;
  opacity: 0.65;
}
/* The default arrow, so hovering the user's own self-toggle does not
 * flash a "blocked" cursor. */
.admin-toggle.disabled :deep(.app-toggle) {
  cursor: default;
}
.dialog-text {
  margin: 0;
}
.reassign-label {
  display: flex;
  flex-direction: column;
  gap: 0.375rem;
  font-size: 0.875rem;
  color: var(--brand-text);
}
</style>

// frontend/src/pages/UsersPage.svelte
<script lang="ts">
import AppButton from "@/components/AppButton.svelte";
import AppCard from "@/components/AppCard.svelte";
import AppDialog from "@/components/AppDialog.svelte";
import AppHeader from "@/components/AppHeader.svelte";
import AppInput from "@/components/AppInput.svelte";
import AppSkeleton from "@/components/AppSkeleton.svelte";
import AppToggle from "@/components/AppToggle.svelte";
import MultiSelectField from "@/components/MultiSelectField.svelte";
import SearchInput from "@/components/SearchInput.svelte";
import {
  approveUser,
  demoteUser,
  promoteUser,
  removeUser,
  renameUser,
  setUserChapters,
  usersQuery,
} from "@/composables/useAdmin.svelte";
import { type Chapter, chaptersQuery, sortedChapters } from "@/composables/useChapters.svelte";
import { guarded } from "@/composables/useGuardedMutation.svelte";
import { t } from "@/i18n.svelte";
import { can } from "@/lib/permissions";
import { useToasts } from "@/lib/toasts";
import { auth } from "@/stores/auth.svelte";
import type { User } from "@/api/types";

/**
 * The accounts of an organisation: approve them, rename them, put them
 * in chapters, make them admins, remove them.
 *
 * Every button asks ``can`` first, so what is on screen matches what
 * the server would allow.
 */
const toasts = useToasts();

const canEdit = (target: User) =>
  can(auth.user, "rename_user", target) || can(auth.user, "set_user_chapters", target);
const canDelete = (target: User) =>
  can(auth.user, "delete_user", target) && target.id !== auth.user?.id;
/** The dialog's admin switch is only worth showing when the actor can
 *  move it both ways, which means an admin editing somebody else. */
const canTogglePromotion = (target: User) =>
  can(auth.user, "promote_user", target) && can(auth.user, "demote_user", target);

const query = usersQuery();
const users = $derived(query.data ?? []);
const approve = approveUser();
const setChapters = setUserChapters();
const promote = promoteUser();
const demote = demoteUser();
const remove = removeUser();
const rename = renameUser();

const askDelete = guarded(remove.run, (u: User) => ({
  vars: u.id,
  ok: t("admin.deleteUserOk", { name: u.name }),
  fail: t("admin.deleteUserFail"),
  confirm: {
    header: t("admin.deleteUserConfirmTitle"),
    message: t("admin.deleteUserConfirmBody", { name: u.name }),
    icon: "exclamation-triangle" as const,
    rejectLabel: t("common.cancel"),
    acceptLabel: t("admin.deleteUser"),
  },
}));

// Only the option pool for the dialog's picker. Chapters themselves are
// managed on their own page.
const chapters = chaptersQuery({ includeArchived: false });
const liveChapters = $derived(sortedChapters(chapters.data));

/** A user's chapters, resolved against the live rows so an upstream
 *  rename shows here too. A membership pointing at a soft-deleted
 *  chapter falls back to the name the user row carries. */
function chaptersForUser(u: User): Chapter[] {
  const live = new Map(liveChapters.map((c) => [c.id, c]));
  return u.chapters
    .map((ref) => live.get(ref.id) ?? (ref as unknown as Chapter))
    .sort((a, b) => a.name.localeCompare(b.name));
}

let search = $state("");

/* Top to bottom: the actor's own row, because it is the likeliest
 * target of anything they do here; the accounts waiting on approval,
 * because clearing those is the job; the other admins; then everyone
 * else. Newest first inside each tier, which keeps the order stable
 * across renders of the same data. */
function tier(u: User, selfId: string | null): number {
  if (u.id === selfId) return 0;
  if (!u.is_approved) return 1;
  if (u.role === "admin") return 2;
  return 3;
}

const sorted = $derived.by(() => {
  const selfId = auth.user?.id ?? null;
  return [...users].sort((a, b) => {
    const byTier = tier(a, selfId) - tier(b, selfId);
    return byTier !== 0 ? byTier : b.created_at.localeCompare(a.created_at);
  });
});

const filtered = $derived.by(() => {
  const q = search.trim().toLowerCase();
  if (!q) return sorted;
  return sorted.filter(
    (u) =>
      u.name.toLowerCase().includes(q) ||
      u.email.toLowerCase().includes(q) ||
      u.chapters.some((c) => c.name.toLowerCase().includes(q)),
  );
});

// --- The one dialog --------------------------------------------------
//
// It covers every write on this page: approving somebody, changing a
// name, changing which chapters they are in, making them an admin or
// not. The mode says which of two it is. Approve needs a chapter and
// sends the approval email; edit fires only the endpoints whose field
// actually changed.
//
// The admin switch is staged: flipping it inside the dialog changes
// nothing until Save.
type EditMode = "approve" | "edit";
let open = $state(false);
let mode = $state<EditMode>("approve");
let target = $state<User | null>(null);
let name = $state("");
let picked = $state<Chapter[]>([]);
let isAdmin = $state(false);
let submitting = $state(false);

function openApprove(u: User): void {
  mode = "approve";
  target = u;
  name = u.name;
  picked = [];
  // Approval always lands as an organiser. Making somebody an admin is
  // a separate, deliberate step.
  isAdmin = false;
  open = true;
}

function openEdit(u: User): void {
  mode = "edit";
  target = u;
  name = u.name;
  const live = new Map(liveChapters.map((c) => [c.id, c]));
  picked = u.chapters.map((ref) => live.get(ref.id)).filter((c): c is Chapter => c !== undefined);
  isAdmin = u.role === "admin";
  open = true;
}

function sameSet(a: string[], b: string[]): boolean {
  if (a.length !== b.length) return false;
  const sb = new Set(b);
  return a.every((x) => sb.has(x));
}

async function submit(): Promise<void> {
  if (!target) return;
  const user = target;

  const trimmed = name.trim();
  if (!trimmed) {
    toasts.warn(t("admin.userEditFillName"));
    return;
  }

  // A chapter is required when editing, because an approved organiser
  // with none is an account that can see nothing. It is optional when
  // approving: they can pick their own from the dashboard's banner.
  if (mode === "edit" && picked.length === 0) {
    toasts.warn(t("admin.userEditPickChapter"));
    return;
  }

  const wanted = picked.map((c) => c.id);
  const current = user.chapters.map((c) => c.id);

  submitting = true;
  try {
    if (mode === "approve") {
      // The rename goes first so the approval email carries the
      // corrected name. Approve takes no name of its own, which keeps
      // both endpoints small and each one auditable.
      if (trimmed !== user.name) await rename.run({ userId: user.id, name: trimmed });
      await approve.run({ userId: user.id, chapterIds: wanted });
      toasts.success(t("admin.approveOk"));
    } else {
      const renamed = trimmed !== user.name;
      const chaptersChanged = !sameSet(wanted, current);
      const roleChanged = isAdmin !== (user.role === "admin");

      if (renamed) await rename.run({ userId: user.id, name: trimmed });
      if (chaptersChanged) await setChapters.run({ userId: user.id, chapterIds: wanted });
      // The role goes last, so a failure earlier cannot leave somebody
      // holding rights the rest of the save never granted them.
      if (roleChanged) {
        if (isAdmin) await promote.run(user.id);
        else await demote.run(user.id);
      }
      if (renamed || chaptersChanged || roleChanged) toasts.success(t("admin.userEditOk"));
    }
    open = false;
  } catch {
    toasts.error(mode === "approve" ? t("admin.approveFail") : t("admin.userEditFail"));
  } finally {
    submitting = false;
  }
}
</script>

<AppHeader />
<div class="container-wide stack">
  <h1>{t("admin.usersTitle")}</h1>
  <p class="muted">{t("admin.usersIntro")}</p>

  <AppCard>
    {#if query.isPending}
      <AppSkeleton rows={4} />
    {:else}
      <SearchInput bind:value={search} placeholder={t("admin.searchPlaceholder")} />
      {#if users.length === 0}
        <p class="muted">{t("admin.empty")}</p>
      {:else if filtered.length === 0}
        <p class="muted">{t("admin.noMatches")}</p>
      {/if}
      {#each filtered as u (u.id)}
        <div class="account-row">
          <div class="account-main">
            <div class="account-identity">
              <strong>{u.name}</strong>
              <span class="muted"> · {u.email}</span>
              {#if u.is_approved && u.role === "admin"}
                <span class="admin-chip">{t("admin.adminToggle")}</span>
              {/if}
            </div>
            <div class="account-actions">
              {#if !u.is_approved}
                <AppButton
                  label={t("admin.approve")}
                  size="small"
                  disabled={!can(auth.user, "approve_user")}
                  onclick={() => openApprove(u)}
                />
              {:else}
                <AppButton
                  icon="pencil"
                  size="small"
                  severity="secondary"
                  text
                  disabled={!canEdit(u)}
                  ariaLabel={t("admin.userEditDialogTitle", { name: u.name })}
                  onclick={() => openEdit(u)}
                />
              {/if}
              <AppButton
                icon="trash"
                size="small"
                severity="secondary"
                text
                disabled={!canDelete(u)}
                ariaLabel={t("admin.deleteUser")}
                onclick={() => askDelete(u)}
              />
            </div>
          </div>
          <!-- The chapter chips get their own row under the name. They
               do not wrap and the row is clipped: somebody in eight
               chapters shows the first few, and the pencil is where the
               whole set is read and changed. -->
          {#if chaptersForUser(u).length > 0}
            <div class="account-chapters">
              {#each chaptersForUser(u) as c (c.id)}
                <span class="chapter-chip">{c.name}</span>
              {/each}
            </div>
          {/if}
        </div>
      {/each}
    {/if}
  </AppCard>

  <AppDialog
    bind:visible={open}
    header={mode === "approve"
      ? t("admin.approveDialogTitle")
      : t("admin.userEditDialogTitle", { name: target?.name ?? "" })}
  >
    <p class="muted dialog-text">
      {mode === "approve"
        ? t("admin.approveDialogBody", { name: target?.name ?? "" })
        : t("admin.userEditDialogBody")}
    </p>
    <label class="reassign-label">
      {t("auth.name")}
      <AppInput
        bind:value={name}
        autocomplete="off"
        fluid
        onkeydown={(e: KeyboardEvent) => e.key === "Enter" && submit()}
      />
    </label>
    <label class="reassign-label">
      {t("admin.chaptersLabel")}
      <MultiSelectField
        bind:value={picked}
        options={liveChapters}
        optionLabel="name"
        placeholder={t("admin.userEditPickChapter")}
        display="chip"
        filter
        fluid
      />
    </label>
    <!-- Staged: flipping this changes nothing until Save. Hidden while
         approving, because a freshly approved account is never an admin
         on the same click. Disabled on your own row, because the server
         refuses self-demotion and the switch should say so before the
         click rather than after it. -->
    {#if mode === "edit"}
      <label class="admin-toggle" class:disabled={!target || !canTogglePromotion(target)}>
        <AppToggle bind:checked={isAdmin} disabled={!target || !canTogglePromotion(target)} />
        <span>{t("admin.adminToggle")}</span>
      </label>
    {/if}
    {#snippet footer()}
      <AppButton
        label={t("common.cancel")}
        severity="secondary"
        text
        onclick={() => (open = false)}
      />
      <AppButton
        label={mode === "approve" ? t("admin.approve") : t("common.save")}
        disabled={!name.trim() || (mode === "edit" && picked.length === 0)}
        loading={submitting}
        onclick={submit}
      />
    {/snippet}
  </AppDialog>
</div>

<style>
/* On a phone the identity truncates and the actions stay pinned to the
 * right of the row. */
@media (max-width: 540px) {
  .account-actions {
    margin-left: auto;
  }
}
.account-row {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
  padding: 0.5rem;
  border-radius: 6px;
  transition: background 120ms ease;
}
.account-row:hover {
  background: var(--brand-surface-100);
}
.account-main {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 0.75rem;
  min-width: 0;
}
.account-identity {
  display: flex;
  align-items: baseline;
  gap: 0.5rem;
  min-width: 0;
  flex: 1;
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}
.account-identity > strong {
  flex-shrink: 0;
}
.account-actions {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  flex-shrink: 0;
}
.account-chapters {
  display: flex;
  flex-wrap: nowrap;
  gap: 0.375rem;
  overflow: hidden;
  white-space: nowrap;
  mask-image: linear-gradient(to right, black 85%, transparent 100%);
  -webkit-mask-image: linear-gradient(to right, black 85%, transparent 100%);
}
.account-chapters .chapter-chip {
  flex-shrink: 0;
}
.admin-chip {
  display: inline-flex;
  align-items: center;
  padding: 0.25rem 0.625rem;
  border-radius: 999px;
  background: color-mix(in srgb, var(--brand-red), transparent 90%);
  color: var(--brand-red);
  font-size: 0.875rem;
  font-weight: 600;
  white-space: nowrap;
}
.admin-toggle {
  display: inline-flex;
  align-items: center;
  gap: 0.375rem;
  font-size: 0.875rem;
  color: var(--brand-text-muted);
  cursor: pointer;
}
.admin-toggle.disabled {
  cursor: default;
  opacity: 0.65;
}
/* The default arrow, so hovering your own switch does not flash a
 * "blocked" cursor. */
.admin-toggle.disabled :global(.app-toggle) {
  cursor: default;
}
.dialog-text {
  margin: 0;
}
.reassign-label {
  display: flex;
  flex-direction: column;
  gap: 0.375rem;
  font-size: 0.875rem;
  color: var(--brand-text);
}
</style>
